### ISSUE TITLE
Unable to search Bhai Gurdas Jee vaars by ang

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#1010]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
Gardas JI Vaaran ang 2, 3 ,4, 5, 6, 7 don't work 
 
What should have happened instead?
Something went wrong page
    
How can the issue be recreated by our team?
search 2 or 3 or 4 or 5, or 6  or 7  (ang) Bhai Gurdas Ji Vaaran

Which web browser are using?
Chrome 

Operating System
Mac OS

Name
Manjinder Singh

**Comment by Gauravjeetsingh** [comment]
This is fixed in prod as well, closing this.
