### ISSUE TITLE
Translation has a strange character

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1028]
The punjabi translation at https://www.sikhitothemax.org/shabad?id=8095&q=rrpk&type=1&source=all&highlight=87326 shows a strange character - 

![image](https://user-images.githubusercontent.com/6245927/79787941-75d43b00-8365-11ea-9ba0-2104f8d44be0.png)

**Comment by saintsoldierx** [comment]
Fixed.
