### ISSUE TITLE
dev and stg should only use stage sttm api

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#1043]
https://stgapi.sikhitothemax.org/

**Comment by Gauravjeetsingh** [comment]
@gurjit03 veerji, we need to fix this, because we can't test bani controller with any deployed version of sttm-web in current scenario.

**Comment by gurjit03** [comment]
@Gauravjeetsingh sure, I am updating the SYNC Local url to stg one shared above. Is there any other url we want to be updated ?
<img width="554" alt="image" src="https://github.com/KhalisFoundation/sttm-web/assets/8514802/ffba4dbb-3a02-44a3-8793-49f0a8c4bcb2">
