### ISSUE TITLE
Add support widget

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1049]
Please include this on all pages for STTM.

<script>
	window.fwSettings={
	'widget_id':63000000151
	};
	!function(){if("function"!=typeof window.FreshworksWidget){var n=function(){n.q.push(arguments)};n.q=[],window.FreshworksWidget=n}}() 
</script>
<script type='text/javascript' src='https://widget.freshworks.com/widgets/63000000151.js' async defer></script>

**Comment by gurjit03** [comment]
@saintsoldierx 
![image](https://user-images.githubusercontent.com/8514802/82674280-af4bdf00-9c60-11ea-883f-6af6d0b0fac7.png)

It's under iframe, so not sure if it can be styled. Your thoughts on this?

**Comment by Gauravjeetsingh** [comment]
Support widget is now workin in prod.
