### ISSUE TITLE
Add author filter to search results

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1051]
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/264">264</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Medium</div>
                       <div> Freshdesk Ticket Description: </div><div class="p1" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica; min-height:
14px">
<strong>Platform: </strong>Web Version</div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica">
<strong>Feedback
Type: </strong>Questions</div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica">
<strong>Describe
Feedback:</strong> How do I limit my search results to a particular Author? I
believe filter on Author was available in earlier versions. It was a useful
feature. Is there a way to do it on latest version?</div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica"> </div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica"><strong>What went
wrong? </strong></div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica"> </div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica"><strong>What should have happened
instead? </strong></div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica"><strong>How can the issue be
recreated by our team? </strong></div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica">
<strong>Browser: </strong>
- </div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica">
<strong>OS:</strong> </div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica"> </div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica">
<strong>What is the desired
functionality?</strong> </div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica">
<strong>What does it currently
do?</strong> </div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica"><span class="Apple-converted-space">  </span></div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica">
<strong>Name</strong> Manmeet
Hora</div>
<div class="p2" style="margin: 0px; font-variant-numeric: normal;
font-variant-east-asian: normal; font-stretch: normal; font-size: 12px;
line-height: normal; font-family: Helvetica">
<strong>E-mail</strong>
manmeet.iitkgp@gmail.com</div>

**Comment by saintsoldierx** [comment]
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/264">264</a> for this issue.</div>

**Comment by navdeepsingh** [comment]
@saintsoldierx can help to describe the desired UI?

**Comment by saintsoldierx** [comment]
@navdeepsingh should be a filter drop down on search and search results page

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/109596933-0cb46c80-7acc-11eb-9053-5b3df47193ef.png)
Similar to this style
