### ISSUE TITLE
Sundar Gutka Support for Sangat Sync

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-web#1055]
If a Sundar Gutka Bani is being displayed, Sangat Sync should update in realtime like it normally would with a Shabad.

**Comment by gurjit03** [comment]
@Gauravjeetsingh Any update on this one. Can we please close this ticket if not planned to work on ?

**Comment by Gauravjeetsingh** [comment]
I am able to open sundar gutka banis which changes in the sangat sync as we change verses in desktop, Closing this out.
