### ISSUE TITLE
Add setting to increase line height

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1062]
It would be great to add a setting to increase line height

**Comment by saintsoldierx** [comment]
@plug-n-play what's the use case? I am not sure what benefit this adds for general users...

**Comment by plug-n-play** [comment]
@saintsoldierx It's an optional setting which IMHO would benefit anyone willing to use it

**Comment by saintsoldierx** [comment]
Ok, @gurjit03 if it's an easy fix, move this under advanced settings for now. Else we can put this in the backlog as it's a nice to have.

**Comment by Gauravjeetsingh** [comment]
This is now in prod as well. Closing it out.
