### ISSUE TITLE
Add option to reach full search results

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1063]
The inline search results don't give full results. It would be nice to have an option labelled similar to `Show all results` and takes the user to see all the search results

**Comment by gurjit03** [comment]
@saintsoldierx @plug-n-play @Gauravjeetsingh do we wanna continue on this? On slack, we discussed that `pagination` control is better which is the current implementation.

**Comment by plug-n-play** [comment]
The ask was never to remove pagination. The ask was to add last list item as view more results which takes the user to exisiting results page

**Comment by gurjit03** [comment]
@plug-n-play got it thanks for clarifying!

**Comment by saintsoldierx** [comment]
@plug-n-play did you test this on sub-pages? It works on homepage but i dont see it working on sub-pages.

**Comment by plug-n-play** [comment]
Sorry I only tested the Home page since the original ask was to add it on Home page. Inner pages use case was missed.
