### ISSUE TITLE
Changes in newer settings panel

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#1073]
- Add tooltips
- Add hover indicators
- Make +- icons larger in dev please esp for mobile
- Display button border radius match the other buttons
- show display options,  font size and dark mode, and hide all others in search results page

**Comment by saintsoldierx** [comment]
Display button border radius match the other buttons - done

**Comment by saintsoldierx** [comment]
We now have new settings panel but do need to add tooltips. 

Hover indicators should already be there.
+- icons should be larger and more mobile friendly.

For this ticket, just adding tooltips would be sufficient.
