### ISSUE TITLE
Fix the travis security risk

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#1078]
Currently, our Travis config file contains node names, ssh port and ssh user.

Look for ways to hide that information from Travis config file, maybe using environment variables.. (From slack convo)

@tsingh777 veerji Adding you here so that you are in touch with what needs to be changed in this issue. :pray:

**Comment by saintsoldierx** [comment]
@Gauravjeetsingh can you work on encrypting the travis.yml account as a priority for right now?

**Comment by tsingh777** [comment]
I'll take a look at this.
