### ISSUE TITLE
Unicode searching doesn't highlight correctly.

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1097]
![image](https://user-images.githubusercontent.com/27791330/83982154-f381e500-a8d8-11ea-86c3-b0186b5e935b.png)

**Comment by AkalUstat** [comment]
I can do this 🤚

**Comment by Gauravjeetsingh** [comment]
Unable to reproduce on dev, tried changing the font to Unicode as well.
Anything else I should be doing to reproduce it @saintsoldierx veerji?

![Screenshot from 2020-06-08 07-41-27](https://user-images.githubusercontent.com/1990932/83986733-79df0b00-a95b-11ea-8395-5fe6d644c523.png)

**Comment by AkalUstat** [comment]
looks to be an issue on ios devices. Am experiencing this on iPhone Xr as well.

**Comment by AkalUstat** [comment]
more specifically safari-based browsers. This issue also appears on mac safari
