### ISSUE TITLE
Type Error with Multiselect

### ISSUE THREAD

**Issue by AkalUstat** [KhalisFoundation/sttm-web#1102]
**Describe the bug**
When you go to a shabad, and then click the forward arrow to the next shabad (and then click anywhere on the document), you get the following error: 
```err
MultiSelect.js:18 Uncaught TypeError: Cannot read property 'contains' of null
    at HTMLBodyElement.<anonymous> (MultiSelect.js:18)
```

Looking at the error after switching to Firefox, it says that `_this.wrapper` is null
*To Reproduce**
1. Go to any shabad
2. Click on next/prev arrow
3. Click anywhere on the document

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Browser Chromium Edge
 - Version 83.0.478.45 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gurjit03** [comment]
@AkalUstat are you still getting this?

**Comment by AkalUstat** [comment]
no longer appears in dev (still in prod)

**Comment by gurjit03** [comment]
okay thanks for testing :+1:
