### ISSUE TITLE
Support Bubble UI Fix

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-web#1107]
**Describe the bug**
Support Bubble hovering too high

<img width="1392" alt="Screen Shot 2020-06-10 at 10 02 04 AM" src="https://user-images.githubusercontent.com/35271830/84296907-9157f880-ab01-11ea-967c-5b8bfa41bf86.png">

Would look better if it was below the footer line

**Comment by saintsoldierx** [comment]
Closing this for now - it is there to stick out and hover on the page. It does look better on sub-pages as it aligns with the buttons on the right hand side for full screen or scroll to top.
