### ISSUE TITLE
Font size number doesnt update

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-web#1108]
Click + or - to change the font size

font size of the text changes but the displayed font size remains stuck at 12

<img width="825" alt="Screen Shot 2020-06-10 at 10 03 59 AM" src="https://user-images.githubusercontent.com/35271830/84297087-d845ee00-ab01-11ea-9c2f-c392f9bb7609.png">
<img width="994" alt="Screen Shot 2020-06-10 at 10 05 09 AM" src="https://user-images.githubusercontent.com/35271830/84297149-ec89eb00-ab01-11ea-92bd-378d966e0416.png">

**Comment by gurjit03** [comment]
@tarunsingh5 veerji are we still getting the issue?

**Comment by saintsoldierx** [comment]
seems to be fixed in dev, not prd. tried in FF
