### ISSUE TITLE
related shabads match coloring

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-web#1110]
We should index the coloring a bit better - im guessing we are just using the scores between 0-100, but 100 would mean its the exact same shabad - i think we should scale it down by bucketing everything over 70 as 70 for coloring purposes 

see this shabad and how it shows up as orange/red but its actually a really strong match

<img width="1197" alt="Screen Shot 2020-06-10 at 10 11 17 AM" src="https://user-images.githubusercontent.com/35271830/84297770-f2340080-ab02-11ea-9cf9-94d90fca6f16.png">

**Comment by tarunsingh5** [comment]
if we multiply each score by 2 and then truncate at 100 wont that do both?

**Comment by saintsoldierx** [comment]
maybe if we multiply by 1.5. I think 2 would be too much.

**Comment by tarunsingh5** [comment]
sounds good to me - we can always iterate if 1.5 is too much / too little

**Comment by plug-n-play** [comment]
This is what we get on stage after the Fix the now:
![image](https://user-images.githubusercontent.com/6245927/86891498-928a3e80-c11c-11ea-81ed-736dac42d475.png)

@tarunsingh5 are we fine with this now?

**Comment by saintsoldierx** [comment]
Tarun Singh confirmed on slack this is ok to close.
