### ISSUE TITLE
Change request: Move newly added "Support" button to footer

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1115]
**Is your feature request related to a problem? Please describe.**
The newly added `Support` button is much of a distraction when ready Baani. 

**Describe the solution you'd like**
Please move this to footer and them it similar to other items so that it doesn't appears prominent when ready Baani

![image](https://user-images.githubusercontent.com/6245927/84603910-c7a1c900-aeaf-11ea-927b-4c7062b67417.png)

**Comment by saintsoldierx** [comment]
This is as designed for the time being.
