### ISSUE TITLE
can't make live search dissappear

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#1122]
**Describe the bug**
quick search stays up even when we click away or do other expected things to remove focus. 
This means I am no longer able to access the drop downs to change to the correct one. This is a UX bug.

![image](https://user-images.githubusercontent.com/644885/84823801-c9fd4380-afd3-11ea-93a1-da2919eaf33f.png)

**To Reproduce**
1. Type something in
2. see live search appear
3. attempt to change search type

**Expected behavior**
clicking away from search box should make live search go away
esc should make live search go away

**Comment by amitojsingh** [comment]
@ManjotS Veer Ji I would like to work on this issue.
