### ISSUE TITLE
Change punjabi translation source

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#1123]
Change the Punjabi translation source from ss to bdb.

Wait on the API to be updated first.

Reference:
![image](https://user-images.githubusercontent.com/1990932/84838626-8567bb80-b058-11ea-8cbf-275c21f7e147.png)

**Comment by plug-n-play** [comment]
@turbanpanda on changing the source, should the current shabad being displayed get updated? I don't see a new XHR call being made

![image](https://user-images.githubusercontent.com/6245927/86890993-c2851200-c11b-11ea-9a32-43cbad303cea.png)

**Comment by saintsoldierx** [comment]
This ticket is just to change the default - not to update on dropdown. But you have a valid issue so please approve this issue and log a new one for the change you mentioned. @plug-n-play @gurjit03

**Comment by plug-n-play** [comment]
Sure
