### ISSUE TITLE
unable to read bhai nand ji vaaraan

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#1125]
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/703">703</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Medium</div>
                       <div> Freshdesk Ticket Description: </div><div dir="ltr">
<div>Hi, I would like to read bhai nand lal ji vaaraan,  but it doesnt show up in the index tab.</div>
<div>Nor if I choose search by "ang" does it give the option of bhai nand lal ji vaaran.</div>
<div>Thanks,</div>
</div>

**Comment by ManjotS** [comment]
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/703">703</a> for this issue.</div>

**Comment by saintsoldierx** [comment]
Let's include this on index page.
