### ISSUE TITLE
Search results don't refresh

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1126]
**Describe the bug**
If we have searched something and search results appear, on changing the source the results don't refresh

**To Reproduce**
1. Open https://stg.sikhitothemax.org/
2. Search something
3. Try changing the Baani source

**Expected behavior**
Changing Baani source should refresh the search results.

**Screenshots**
![image](https://user-images.githubusercontent.com/6245927/85042444-d7b7f200-b1a8-11ea-98cc-0624f3c55802.png)

**Comment by saintsoldierx** [comment]
@ManjotS based on our recent convo, is this use case valid?

**Comment by ManjotS** [comment]
I dont like the auto refreshing personally. Once we add the other drop downs, the decision is up to you if we should auto refresh or not.

**Comment by gurjit03** [comment]
Closing this ticket for now
