### ISSUE TITLE
Search results should clear when Ang search is selected

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1127]
**Describe the bug**
Search results don't clear when Ang search is selected after something has been searched with valid results.

**To Reproduce**
1. Go to https://stg.sikhitothemax.org/
2. Try searching something which returns valid search results.
3. Try changing searching type to `Ang`
4. Observe that search input gets cleared but not the search results

**Expected behavior**
Search results should clear when Ang search is selected, after a search with valid search results.

**Screenshots**
![image](https://user-images.githubusercontent.com/6245927/85044349-1c448d00-b1ab-11ea-8740-890b314b7514.png)

**Comment by saintsoldierx** [comment]
i also noticed it adds letter in when changing to ang 
![image](https://user-images.githubusercontent.com/27791330/85193549-73676200-b27e-11ea-8415-9dc25cf2a308.png)

**Comment by plug-n-play** [comment]
@gurjit03 I don't see any network calls being made on changing the search type
![image](https://user-images.githubusercontent.com/6245927/86890244-a0d75b00-c11a-11ea-88b0-ecf0b1ecf4f6.png)

**Comment by gurjit03** [comment]
@plug-n-play actually I have just cleared the search results, if we are changing from any search type to ang considering it wasn't valid search result for ang [ as ang is based on number]. Do we have any overlapping cases?

**Comment by plug-n-play** [comment]
As an end user, I would expect results to change on changing the search type.

@saintsoldierx thoughts?

**Comment by saintsoldierx** [comment]
I agree with @plug-n-play. If this is high LOE then we should create a new issue in GH for enhancement

**Comment by saintsoldierx** [comment]
@gurjit03 up to you - either fix or create new issue.

**Comment by gurjit03** [comment]
@saintsoldierx @plug-n-play thanks veerji. Yeah I would create new issue.
