### ISSUE TITLE
Changing font-size from Drop-down doesn't applies it

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1128]
**Describe the bug**
Changing font-size from Drop-down doesn't applies it

**To Reproduce**
1. Go to https://stg.sikhitothemax.org/shabad?id=5538
2. Click on `Font-size`'s drop-down
3. Observe that on selecting one of the sizes, it doesn't gets applied

**Expected behavior**
Selected font-size should apply on selection.

**Screenshots**

![image](https://user-images.githubusercontent.com/6245927/85045105-2915b080-b1ac-11ea-9e28-d3084afc9675.png)

**Comment by saintsoldierx** [comment]
same with line-height in dev currently. Please do testing in all major browsers for all dropdowns too. @gurjit03

**Comment by plug-n-play** [comment]
Working as expected. Closing Issue
