### ISSUE TITLE
Increase default line-height so Baani doesn't overlaps

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1130]
**Describe the bug**
Baani overlaps in the settings shared in the screenshot.

**To Reproduce**
Change the settings to those described in the screenshot

**Expected behavior**
Default line-height should be increased.

**Screenshots**
![image](https://user-images.githubusercontent.com/6245927/85215903-617be100-b39c-11ea-8e74-1b1a6569c465.png)

**Comment by tarunsingh5** [comment]
100% we shouldnt allow a line height that causes overlap at all

**Comment by plug-n-play** [comment]
Verified on stg.sikhitothemax.org to be working as expected
![image](https://user-images.githubusercontent.com/6245927/86888730-4a691d00-c118-11ea-8163-ec2e0253c219.png)

![image](https://user-images.githubusercontent.com/6245927/86888745-5228c180-c118-11ea-99d3-a73c54251d45.png)

Closing Issue

**Comment by plug-n-play** [comment]
Please remove line height option of 1. Minimum should be 1.2
![image](https://user-images.githubusercontent.com/6245927/86893110-c8302700-c11e-11ea-910e-71a01e632483.png)

**Comment by saintsoldierx** [comment]
@gurjit03 can remove 1.0 option.

**Comment by gurjit03** [comment]
:+1:
