### ISSUE TITLE
Sangat Sync scroll in full screen

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-web#1139]
**Describe the bug**
When in full screen at sangat sync , the scroll is little off.

**To Reproduce**
1. Go to sangat sync
2. Connect to desktop
3. Make sure you are on full screen
4.Change the verse from desktop and you will see that scroll is a bit off

**Comment by saintsoldierx** [comment]
Unable to reproduce. Please reopen if you still see issue @inderpreetsingh
