### ISSUE TITLE
add new shortcuts

### ISSUE THREAD

**Issue by AkalUstat** [KhalisFoundation/sttm-web#1160]
1. quickly changing to unicode for copying
2. fullscreen 
3. dark mode
4. font size up and down

**Comment by AkalUstat** [comment]
actually with the fullscreen it might just be vimium messing with me

**Comment by AkalUstat** [comment]
never mind

**Comment by tarunsingh5** [comment]
@saintsoldierx for UI

**Comment by saintsoldierx** [comment]
For UI, I would like each setting in the right panel to have a tool tip that shows keyboard shortcut.

I would also like a button on top of settings panel which will switch the setting panel between normal setting mode and a list of keyboard shortcuts in two columns.

These are existing shortcuts:

Larivaar | l |  
-- | -- | --
Larivaar Assist | Shift + l |  
Vishraams | v |  
Autoscroll Mode | a |  
Center Align | CMD + Shift + c | Ctrl + Shift + c
English Translation | e |  
Punjabi Translation | t |  
Spanish Translation | s |  
English Transliteration | Shift + e |  
Shahmukhi Transliteration | Shift + s |  
Hindi Transliteration | Shift + h |  
Search Bar | CMD + / | ctrl + /

**To add:** 
u | switch to unicode
f | fullscreen mode
o | light mode/dark mode toggle
+- | increase or decrease font size of ALL 
/ | split mode
r | reading (akhand paath mode)
