### ISSUE TITLE
Make UX better to close Advanced Settings

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1164]
As of now, when `Advanced` are open, it can be confusing to new users on how to close the Advanced settings
![image](https://user-images.githubusercontent.com/6245927/87217939-2b62c900-c36c-11ea-8c9d-43ad2030f1a7.png)

Recommendation:
1. Add a cross icon to close the Advanced Settings panel in addition to the existing option to close it
2. Change the UI state of `Advanced` control to distinguish between open and close states

**Comment by gurjit03** [comment]
@saintsoldierx veerji, can you suggest UI state changes for `advanced` button ?

**Comment by saintsoldierx** [comment]
For now, a X in top right corner @gurjit03
