### ISSUE TITLE
Remove Express Server

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1166]
Removing Express Server from our flow would help us move in the direction of deploying sttm.co to CDNs like Amazon S3, amongst several other process benefits to follow

**Comment by gurjit03** [comment]
@plug-n-play veerji, any suggestions how can we achieve that template rendering which we are doing for meta tags atm ?

**Comment by plug-n-play** [comment]
https://github.com/nfl/react-helmet helps with that

**Comment by plug-n-play** [comment]
Had a conversation with @bogas04 

If we remove server and rely on react-helmet, we would loose SEO, as meta tags would get updated on client side.

We should instead aim to move static assets to S3 and let the Server as is. Will close this ticket and create a new one.
