### ISSUE TITLE
Shabad page scrolls past highlighted line

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1174]
On sttm.co search for a line in a shabad and go to it - the webpage should auto scroll to that line on the shabad page but at moment it goes past the line to next one. eg. 

https://www.sikhitothemax.org/shabad?id=2610&q=bhbgg&type=0&source=G&highlight=29479

**Comment by plug-n-play** [comment]
Observed this to be highlighting the searched line - https://khalis-herok-fix-highli-bi6pyh.herokuapp.com/shabad?id=2610&q=bhbgg&type=0&source=G&highlight=29479
