### ISSUE TITLE
Sohila Sahib in Sundar Gutka not showing translations

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1176]
![image](https://user-images.githubusercontent.com/27791330/87504592-caf9b300-c61b-11ea-86c3-d38001692228.png)

![image](https://user-images.githubusercontent.com/27791330/87504555-adc4e480-c61b-11ea-874f-a85ff84506ec.png)

**Comment by plug-n-play** [comment]
Fix working in https://khalis-herok-fix-sohila-zuibkc.herokuapp.com/
