### ISSUE TITLE
Add writer on all Shabad description panels

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#1188]
From email:
Feedback for website.  Can you put the Writer on the description on all Shabads.  Since any Pauree does not have M:3 etc.

**Comment by tarunsingh5** [comment]
does this data exist in the db? what do you do about things like salok fareed ji ke where writers switch often?

**Comment by tsingh777** [comment]
Each verse has a writer.

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/103044277-d5a66580-4534-11eb-997e-748c06b4ba18.png)
It can go underneath Punjabi and English together on one line: eg. ਗੁਰੂ ਅਰਜਨ Guru Arjan Dev Ji

**Comment by tsingh777** [comment]
Angs/Banis can have multiple writers. Make an API ticket if having you want a new endpoint that gives you list of all writers for an ang/bani.
