### ISSUE TITLE
Consider changing to more modern fonts

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#120]
ie open sans and the like

@navdeepsinghkhalsa @bogas04 id like your input on this

especially want to do this in #metadata etc

**Comment by bogas04** [comment]
Any decision made on this? @tarunsingh5

**Comment by ManjotS** [comment]
we want to do it its just low priority

**Comment by saintsoldierx** [comment]
@ManjotS what does this entail? Which fonts/text need changing?

**Comment by ManjotS** [comment]
8 think this falls under redesign. I want to use more modern fonts for
English.

**Comment by saintsoldierx** [comment]
We decided to go with Lato (Google fonts)

**Comment by Gauravjeetsingh** [comment]
@saintsoldierx veerji, currently Lato is used only in the footer, and we are using Muli everywhere else. Is this a bug or intentional?

**Comment by saintsoldierx** [comment]
Hanji yes it’s intentional. See discussion in slack #design with Manjot Singh.
