### ISSUE TITLE
Add facebook icon to line sharer

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#121]

**Comment by bogas04** [comment]
We don't have FB in Line Sharer as of now for unknown reasons. Could you tell why it was disabled? @ManjotS @tarunsingh5

**Comment by ManjotS** [comment]
afaik it was never implemented. the work was either you or @navdeepsinghkhalsa 

this ticket is to implement it

**Comment by tarunsingh5** [comment]
the line sharers are really annoying on mobile i think we should scrap them on mobile

**Comment by bogas04** [comment]
They are scrapped.

**Comment by bogas04** [comment]
Nope.

**Comment by bogas04** [comment]
Given the data, we'll be swapping Twitter for Facebook and monitor data. If more people start using it over copy substantially, we'll let it be, else we'll only have copy.

**Comment by bogas04** [comment]
https://github.com/KhalisFoundation/sttm-web/tree/feature/facebook-line-sharer
