### ISSUE TITLE
Remove progress indicator atleast in full screen mode

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1221]
**Is your feature request related to a problem? Please describe.**
The progress indicator on top is a distraction when reading Baani
![image](https://user-images.githubusercontent.com/6245927/91435007-47bab680-e883-11ea-8df7-4a9b2f0cf42e.png)

**Describe the solution you'd like**
It would be great if we can remove it atleast in Full-screen mode if not altogether.

**Comment by saintsoldierx** [comment]
We decided to leave the progress bar in, many do like the feature. We will hide it if using Sehaj Paath mode.
