### ISSUE TITLE
Doodle image is quite heavy and causes a lot of layout shift on page load

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#1233]
**Describe the bug**
Doodle image loads quite slowly and causes a layout shift. Either ensure it's same height as the logo so as to avoid layout shift, or load it as a background image (like bing) for large doodles.

**To Reproduce**
1. Open sikhitothemax.org
2. Observe

**Expected behavior**
Page should load without layout shifts causing incorrect taps.

**Screenshots**
![layout](https://user-images.githubusercontent.com/6177621/91709982-27e80300-eba1-11ea-883c-1863961bf953.gif)

**Comment by saintsoldierx** [comment]
I think the load time really depends on connection speed, we will optimize the images to load faster in future.

**Comment by bogas04** [comment]
That isn't the fix. You need to provide height and width to img tag so that even if image hasn't loaded, it takes the necessary space instead of causing a layout shift.

Similarly, the decision to show logo or doodle should be eagerly made before page load so that user doesn't see a splash of logo before seeing the image.

**Comment by saintsoldierx** [comment]
Ah sure, i get what you're saying @bogas04

**Comment by saintsoldierx** [comment]
@ManjotS can you just confirm we are able to specify height and width in api? In which case we just need to add it at presentation layer.

**Comment by ManjotS** [comment]
Yes, by design API is providing height, width, custom CSS. I even specified
at implementation that web should use all of the available.

**Comment by gurjit03** [comment]
Fixed already
