### ISSUE TITLE
Keyboard shortcuts shouldn't act when using browser keyboard shortcuts

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#1236]
**Describe the bug**
Browser keyboard shortcut Command + L (to go to addressbar) gets caught by the website to toggle larivar mode.

**To Reproduce**
1. Open any shabad
2. Press command + L (or control + L on non-mac)
3. Observe

**Expected behavior**
Addressbar should be highlighted without toggling larivaar mode.

**Screenshots**
![command l](https://user-images.githubusercontent.com/6177621/91711560-b5c4ed80-eba3-11ea-852b-cd4f80ae31b8.gif)

**Comment by AkalUstat** [comment]
this is a bug with the keyboard shortcut library i believe
