### ISSUE TITLE
Changing Ang doesn't update content

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1239]
**Describe the bug**
Changing Ang doesn't update content.

https://khalis.slack.com/files/U2UP3HM3L/F019TKWC97C/record_2020-08-31-21-36-33.mp4

**Comment by saintsoldierx** [comment]
This is a P1 issue @gurjit03 

The infinity scroll means when typing in ang 5, it loads all angs 1-5.
