### ISSUE TITLE
Hide "null" values in related shabad cards. 

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-web#1253]
![image](https://user-images.githubusercontent.com/2982784/93496680-5fa2ba80-f8c4-11ea-86a6-fbdf40e4cf97.png)

**Comment by gurjit03** [comment]
@tsingh777 @saintsoldierx veerji, are we still facing this issue?

**Comment by tsingh777** [comment]
@gurjit03 yes. Here's an example https://www.sikhitothemax.org/shabad?id=30074&q=spAn&type=0&source=all&highlight=402060

**Comment by gurjit03** [comment]
@tsingh777 veerji, it might not be merged yet with production

**Comment by saintsoldierx** [comment]
Issue has been fixed.
