### ISSUE TITLE
Add Hukamnama Audio 

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1261]
https://github.com/KhalisFoundation/hukamnama-json/pull/25

Add a way to play Hukamnama from Sri Harimandir Sahib audio from the Hukamnama page.

**Comment by plug-n-play** [comment]
Don't see a control on UI to play Hukamnama audio

**Comment by saintsoldierx** [comment]
This works - just missing data in DEV/STG
