### ISSUE TITLE
Add a calendar to Hukamnama

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1265]
Add calendar function on Hukamnama to be able to search previous Hukamnamas from any given date. We may only be able to go back to around Jan 1, 2020 as of now.

**Comment by tarunsingh5** [comment]
@ManjotS lets figure out how to go back further

**Comment by ManjotS** [comment]
Ns pulled like 10 years. Will revisit and check oldest date.

**Comment by plug-n-play** [comment]
1. In stage, past Hukamnama is loading by default:
![image](https://user-images.githubusercontent.com/6245927/99796510-a080af00-2b53-11eb-9cbb-526bee42cfcb.png)

2. Why do we have the option `Go to shabad` since both versions have same Shabad content?
