### ISSUE TITLE
Steek turns back on back after refreshing

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#1283]
- Open any Shabad
- Click on the Steek option
- Click again to disable it
- Refresh the page
- The steek is still on

![Peek 2020-10-21 20-18](https://user-images.githubusercontent.com/1990932/96737029-d870c700-13da-11eb-800b-1896b3618d53.gif)

**Comment by saintsoldierx** [comment]
Seems to be fine if you uncheck "Punjabi" under translation but gives issue when unchecking steek directly. Also i noticed when u refresh, it unchecks punjabi. If a steek is checked, Punjabi should always be checked.

**Comment by gurjit03** [comment]
@saintsoldierx veerji can you please the exact steps for reproducing this
