### ISSUE TITLE
Fix failing automated test cases

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1295]
Fix failing automated test cases:

![image](https://user-images.githubusercontent.com/6245927/98008767-d830ec80-1e1a-11eb-9a71-b0a996ea6b51.png)

**Comment by plug-n-play** [comment]
@gurjit03 following tests are still failing:

![image](https://user-images.githubusercontent.com/6245927/99790095-a1144800-2b49-11eb-98f4-06635113047e.png)

![image](https://user-images.githubusercontent.com/6245927/99790153-b4271800-2b49-11eb-8bec-952b8500a6fd.png)

**Comment by gurjit03** [comment]
@plug-n-play veerji, I will have a look now !
