### ISSUE TITLE
Faster Auto Scroll

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#1306]
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/2717">2717</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Medium</div>
                       <div> Freshdesk Ticket Description: </div><div>The Auto Scroll is really slow, can you <span class="caps">PLEASE</span> make it faster?</div>

**Comment by ManjotS** [comment]
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/2717">2717</a> for this issue.</div>

**Comment by saintsoldierx** [comment]
It seems to be that although it's a slider to control speed, there are only four speeds available. This should not be the case, it should be more responsive to the slider.

**Comment by plug-n-play** [comment]
I observe that the max speed on Stage is now increased. However, after a few seconds, the scroll speeds gets decreased automatically

https://youtu.be/G3maIsudrfc

**Comment by saintsoldierx** [comment]
Haven't had any complaints and doesn't seem to slow down for me so going to close this for now.
