### ISSUE TITLE
Auto scroll Mode: Restart again from top/start after reaching end/bottom of shabad page

### ISSUE THREAD

**Issue by iamnavpreet** [KhalisFoundation/sttm-web#1307]
We wanted to use website based Hukamnama display (browser in SMART TV ) in Gurudwara. We loved the feature of Auto scroll and it really helps the way we wanted to display.

We observed that, once the page scroll is completed, it stands there. Manually we need to click to go to the start/top of the page to start auto scroll again. 

`We want an option in which we can have a checkbox saying we want to autoscroll loop [ yes / no ]`

or

`We want Autoscroll feature to do go in loop again without any checkbox selected.`

Using this feature will make perfect solution to use STTM web in Smart TV

**Comment by saintsoldierx** [comment]
In short, we need an option in settings to allow for loop IF autoscroll mode is on. When reaching bottom of the Hukamnama, screen should go to top and start scrolling again - repeat infinitely.

**Comment by gurjit03** [comment]
@saintsoldierx This should be fixed
