### ISSUE TITLE
Ang search reverts to source=all

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1308]
**Describe the bug**
After initial search, the ang search looks for source=all even though source of Sri Guru Granth Sahib Ji is selected.

**To Reproduce**
1. Go to sikhitothemax.org
2. Search for ang 4 of Sri Guru Granth Sahib Jee. It goes to the right page.
3. Click on STTM logo at top to go to homepage
4. Now search for ang 5 - it brings error with source=all in URL.

Chrome / OS X

**Comment by plug-n-play** [comment]
This is working as expected for me in both Prod and Stage. Has the fix already been pushed to prod?
