### ISSUE TITLE
Keyboard doesn't auto closes on opening  Sundar Gutka Baani

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1311]
**Describe the bug**
Keyboard doesn't auto closes on opening  Sundar Gutka Baani.

**To Reproduce**
1. Go to https://www.sikhitothemax.org/sundar-gutka
2. Click on keyboard
3. Open any Baani. Notice keyboard is still open

![image](https://user-images.githubusercontent.com/6245927/99794209-d58b0280-2b4f-11eb-90a1-59f7ff29c78b.png)

**Expected behavior**
Keyboard should get closed automatically when Baani is opened.

**Comment by saintsoldierx** [comment]
Good catch. I think across the site, the keyboard should hide if you click off it.

**Comment by plug-n-play** [comment]
Looks good on stage env.

**Comment by saintsoldierx** [comment]
@plug-n-play you reopened this but it's fixed in production... Can you check?
