### ISSUE TITLE
Clicking BaniDB translation setting on shabad page closes the dialog

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1324]
When on a shabad, open DISPLAY panel and check BaniDB - it auto closes when turning it on (does not close when turning off).

**Comment by gurjit03** [comment]
@saintsoldierx Not able to reproduce this on linux chrome/firefox.
I clicked on the bani DB and the options don't autoclose for me.

**Comment by saintsoldierx** [comment]
Seems to be fine now.
