### ISSUE TITLE
Punjabi Translation setting should also select BaniDB as default.

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#1333]
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/3099">3099</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Low</div>
                       <div> Freshdesk Ticket Description: </div><div>I am analysing this from a long time now, almost a month i think. Punjabi Translation is not working whenever i click random shabad section. I have not checked other sections. I tried from my other iOs phone but it is not working. I am using an iPhone. Please see <br>Thank you <br>Waheguru Ji Ka Khalsa<br>Waheguru Ji Ki Fateh</div>

**Comment by ManjotS** [comment]
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/3099">3099</a> for this issue.</div>

**Comment by plug-n-play** [comment]
Working as expected on Stage:
![image](https://user-images.githubusercontent.com/6245927/104152652-2e677080-5406-11eb-9f18-6563781b2a2c.png)

Prod:
![image](https://user-images.githubusercontent.com/6245927/104152669-3a533280-5406-11eb-9f6e-03fad13e48d3.png)
