### ISSUE TITLE
Amrit Keertan shabads are not displayed in correct template

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1335]
Should have side spacing 

![image](https://user-images.githubusercontent.com/27791330/103508519-fb294e00-4e15-11eb-8175-5f1d30ef4851.png)

**Comment by plug-n-play** [comment]
Sorry, not clear on what is the requirement here. Please share the prod url to compare how it currently looks in live environment.

**Comment by plug-n-play** [comment]
Working as expected on stage:
![image](https://user-images.githubusercontent.com/6245927/104152271-0deae680-5405-11eb-9bde-e5efac39fa97.png)


Prod:
![image](https://user-images.githubusercontent.com/6245927/104152258-01668e00-5405-11eb-8484-fa7068618589.png)
