### ISSUE TITLE
Please add Hindi or Devanagari in the app 

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#134]
User report.. this can easily be done with the gurbani hindi font we created in our other repo (using the current text in gurmukhi data).

Please test extensively.

**Comment by bogas04** [comment]
Can we do this with anvaad? @navdeepsinghkhalsa

**Comment by navdeepsinghkhalsa** [comment]
@bogas04 Yes, the first step would be to make it available via API, which uses anvaad-js to do all the conversions when edits are made.

**Comment by ManjotS** [comment]
I'm thinking we can just use anvaad translit module and have hindi transliteration?

**Comment by ManjotS** [comment]
https://github.com/KhalisFoundation/anvaad-js/issues/18

**Comment by navdeepsinghkhalsa** [comment]
It should be returned by the API

**Comment by saintsoldierx** [comment]
@navdeepsinghkhalsa @ManjotS can you update the ticket on where we are with this?

**Comment by Gauravjeetsingh** [comment]
Here's the PR #831
