### ISSUE TITLE
Search should not be case sensitive

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1372]
When searching in English, search should not be case sensitive. eg.

![image](https://user-images.githubusercontent.com/27791330/113206420-4a6bf880-9224-11eb-8110-71993bce57e4.png)
--
![image](https://user-images.githubusercontent.com/27791330/113206457-55bf2400-9224-11eb-859f-a13a2612ad8a.png)

**Comment by tsingh777** [comment]
This is an API issue. I can take a look.

**Comment by saintsoldierx** [comment]
Closing this as it's a BaniDB API issue.
