### ISSUE TITLE
Khakha with Bindhi character needs to be added to first/anywhere letter search keyboard

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1374]
Need to add pehri khakha character to the keyboard for letter search because at the moment, there is no fuzzy search. You cannot find Khalsa mero roop hai khaas without pehri khakha

![image](https://user-images.githubusercontent.com/27791330/113501100-de191f80-94d7-11eb-8685-ef00d13b7d3c.png)

**Comment by gsin11** [comment]
Has been fixed on DEV.
