### ISSUE TITLE
Update help page with newer UI

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#1375]
**Describe the bug**
The current help page shows screenshots of old UI of sttm-web

**To Reproduce**
1. Go to https://www.sikhitothemax.org/help
2. Scroll down to see the screenshots.
 
**Expected behavior**
Update those screenshots with current UI

**Screenshots**
![image](https://user-images.githubusercontent.com/1990932/113541646-47944d80-9600-11eb-99b2-271142cce666.png)

**Comment by saintsoldierx** [comment]
@Gauravjeetsingh you need to update STTM desktop to use new help system https://support.khalisfoundation.org/support/solutions/folders/63000040721
