### ISSUE TITLE
Add filters and redesign search page

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1406]
![image](https://user-images.githubusercontent.com/27791330/116035557-08af5180-a61a-11eb-8a84-4b74cafeb1ac.png)

**Comment by Kuljeet-123** [comment]
@saintsoldierx can I work on this issue??

**Comment by gurjit03** [comment]
@saintsoldierx This looks very neat, we can surely work on this once we have support from the api for the writers/raags.

**Comment by gurjit03** [comment]
@saintsoldierx This needs api support so closing this for now
