### ISSUE TITLE
Copy using unicode and split mode layout issue

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1408]
**CURRENT OUTPUT WHEN USING COPY BUTTON:-**

 ਦੇਵਗੰਧਾਰੀ  ਮਹਲਾ  ੯  ॥ 

 ਜਗਤ  ਮੈ  ਝੂਠੀ  ਦੇਖੀ  ਪ੍ਰੀਤਿ  ॥ 

 ਅਪਨੇ  ਹੀ  ਸੁਖ  ਸਿਉ  ਸਭ  ਲਾਗੇ  ਕਿਆ  ਦਾਰਾ  ਕਿਆ  ਮੀਤ  ॥੧॥  ਰਹਾਉ  ॥ 

 ਮੇਰਉ  ਮੇਰਉ  ਸਭੈ  ਕਹਤ  ਹੈ  ਹਿਤ  ਸਿਉ  ਬਾਧਿਓ  ਚੀਤ  ॥ 

 ਅੰਤਿ  ਕਾਲਿ  ਸੰਗੀ  ਨਹ  ਕੋਊ  ਇਹ  ਅਚਰਜ  ਹੈ  ਰੀਤਿ  ॥੧॥ 

 ਮਨ  ਮੂਰਖ  ਅਜਹੂ  ਨਹ  ਸਮਝਤ  ਸਿਖ  ਦੈ  ਹਾਰਿਓ  ਨੀਤ  ॥ 

 ਨਾਨਕ  ਭਉਜਲੁ  ਪਾਰਿ  ਪਰੈ  ਜਉ  ਗਾਵੈ  ਪ੍ਰਭ  ਕੇ  ਗੀਤ  ॥੨॥੩॥੬॥੩੮॥੪੭॥ 
Raag Dayv-Gandhaaree, Ninth Mehla:In this world, I have seen love to be false.Whether they are spouses or friends, all are concerned only with their own happiness. ||1||Pause||All say, ""Mine, mine"", and attach their consciousness to you with love.But at the very last moment, none shall go along with you. How strange are the ways of the world! ||1||The foolish mind has not yet reformed itself, although I have grown weary of continually instructing it.O Nanak, one crosses over the terrifying world-ocean, singing the Songs of God. ||2||3||6||38||47||

**SHOULD BE:-**

 ਦੇਵਗੰਧਾਰੀ  ਮਹਲਾ  ੯  ॥ 
 ਜਗਤ  ਮੈ  ਝੂਠੀ  ਦੇਖੀ  ਪ੍ਰੀਤਿ  ॥ 
 ਅਪਨੇ  ਹੀ  ਸੁਖ  ਸਿਉ  ਸਭ  ਲਾਗੇ  ਕਿਆ  ਦਾਰਾ  ਕਿਆ  ਮੀਤ  ॥੧॥  ਰਹਾਉ  ॥ 
 ਮੇਰਉ  ਮੇਰਉ  ਸਭੈ  ਕਹਤ  ਹੈ  ਹਿਤ  ਸਿਉ  ਬਾਧਿਓ  ਚੀਤ  ॥ 
 ਅੰਤਿ  ਕਾਲਿ  ਸੰਗੀ  ਨਹ  ਕੋਊ  ਇਹ  ਅਚਰਜ  ਹੈ  ਰੀਤਿ  ॥੧॥ 
 ਮਨ  ਮੂਰਖ  ਅਜਹੂ  ਨਹ  ਸਮਝਤ  ਸਿਖ  ਦੈ  ਹਾਰਿਓ  ਨੀਤ  ॥ 
 ਨਾਨਕ  ਭਉਜਲੁ  ਪਾਰਿ  ਪਰੈ  ਜਉ  ਗਾਵੈ  ਪ੍ਰਭ  ਕੇ  ਗੀਤ  ॥੨॥੩॥੬॥੩੮॥੪੭॥ 

Raag Dayv-Gandhaaree, Ninth Mehla:
In this world, I have seen love to be false.
Whether they are spouses or friends, all are concerned only with their own happiness. ||1||Pause||
All say, ""Mine, mine"", and attach their consciousness to you with love.
But at the very last moment, none shall go along with you. How strange are the ways of the world! ||1||
The foolish mind has not yet reformed itself, although I have grown weary of continually instructing it.
O Nanak, one crosses over the terrifying world-ocean, singing the Songs of God. ||2||3||6||38||47||

**Comment by navdeepsingh** [comment]
@saintsoldierx 

![image](https://user-images.githubusercontent.com/2968787/123413737-bc0fd480-d5d0-11eb-97d8-1e40fed9561a.png)

Right now, extra spaces are removed. Please check the preview. I feel it's legit.
