### ISSUE TITLE
Change icon for Transliteration

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1442]
In display settings, `Transliteration` option currently uses industry standard speech icon
<img width="349" alt="image" src="https://user-images.githubusercontent.com/6245927/118749383-076cef80-b87b-11eb-8489-120f68e28ae5.png">

but is not directly related to user's speech. We have an opportunity to use a better icon and remove this confusion.

**Comment by navdeepsingh** [comment]
@saintsoldierx please suggest an icon.

**Comment by saintsoldierx** [comment]
[talk.svg.zip](https://github.com/KhalisFoundation/sttm-web/files/6525936/talk.svg.zip)

**Comment by gurjit03** [comment]
@saintsoldierx This issue is already completed and merged(https://github.com/KhalisFoundation/sttm-web/pull/1476)
![Selection_041](https://user-images.githubusercontent.com/8514802/162179015-4cecc71c-4f53-4a33-b64b-224fe38252de.png)
