### ISSUE TITLE
Ang, akhand paath mode gives error when trying to continue

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1448]
1. Going to ang view
2. Enabling akhand paath mode
3. Scroll down page
4. Go to home page
5. try to continue - produces error. 

Navdeep Singh able to replicate. 

[SikhiToTheMax_AngError_ReproducibleSteps.webm.zip](https://github.com/KhalisFoundation/sttm-web/files/6551370/SikhiToTheMax_AngError_ReproducibleSteps.webm.zip)

**Comment by ManjotS** [comment]
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/4743">4743</a> for this issue.</div>
