### ISSUE TITLE
Evaluate and add brotli

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#145]
https://certsimple.com/blog/nginx-brotli

**Comment by bogas04** [comment]
In my own research, `brotli` is great (20% compression improvement over gzip), however its compression time is pathetic, and is meant to be compiled before hand as opposed to compressing on the fly. If we can support that, then we should definitely go for it, as all [modern browsers support it](https://caniuse.com/#feat=brotli).

I can setup our build process to also produce `.br` files, which can then be sent to CDN, and nginx can be updated to serve it (brotli-static)

**Comment by ManjotS** [comment]
this pretty low priority, especially if you aren't confident in it.

**Comment by bogas04** [comment]
@navdeepsinghkhalsa What can I do to make this happen? I can produce brotli JS assets at build step to begin with.

**Comment by navdeepsinghkhalsa** [comment]
@bogas04 That's great that you are ready for this at the front-end. Just need to evaluate if it's something we want to do. I will take a look after this sprint closes.

**Comment by bogas04** [comment]
20% better compression at no cost. Just that we need to pre-build the files.

**Comment by saintsoldierx** [comment]
This ticket still valid @ManjotS

**Comment by ManjotS** [comment]
@tsingh777 please let us know

**Comment by saintsoldierx** [comment]
@tsingh777

**Comment by saintsoldierx** [comment]
ping @tsingh777

**Comment by tsingh777** [comment]
Would like to see if https://github.com/expressjs/compression/pull/172 gets accepted. keep it open at low priority.

**Comment by gurjit03** [comment]
This needs more discussion/research and might be even avoidable if we opt for next.js or any other framework.
