### ISSUE TITLE
Reduce width of auto-scroll component when not in use for few seconds

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1479]
Kindly reset the width of the auto-scroll component when it is not in use for a few seconds (say 3 seconds)

![image](https://user-images.githubusercontent.com/6245927/142767242-1059599e-f075-4400-bc45-fda5bf1f6388.png)

As of now, the auto-scroll component placed at bottom right of the screen increases it's width when auto-scroll is turned on. But it stays there and overlaps with Baani as shown in screenshot above. This is especially problematic in mobile view

It would be nice to reset it to it's regular width (or even better, hide it, especially in mobile view) when not in use and expand it again (or show it back if hidden) when user scrolls mouse again/touches the mobile device.

**Comment by gsin11** [comment]
I just did a feasibility check on Mobile devices.
1. We can remove the full-screen icon from mobile devices, I am sure it is useful on desktop devices only (please correct, if I am wrong).
2. Button size can be reduced to a certain extend, please find below a screenshot with my proposal.

# Before
![image](https://user-images.githubusercontent.com/3865313/145789492-e352d0b0-7a77-4219-9b42-d1b57e18454d.png)

# After
![image](https://user-images.githubusercontent.com/3865313/145789186-b1076070-8084-4912-8b82-bd1ca26bf59a.png)

CC: @saintsoldierx

**Comment by saintsoldierx** [comment]
I like the reduced size idea @gsin11

**Comment by gurjit03** [comment]
@saintsoldierx closing this issue as it's fixed already
