### ISSUE TITLE
Use dev api in stg deployment.

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#1481]
Currently both versions of the sttm-web are using the prod sikhitothemax api. 
- https://www.sikhitothemax.org/control sends request to https://api.sikhitothemax.org/sync/
- https://stg.sikhitothemax.org/control sends request to same api at https://api.sikhitothemax.org/sync/

The stg deployment should use the stgapi.sikhitothemax.org/sync instead.

Because of this we are unable to QA the bani controller alpha release before releasing it to prod.

**Comment by gurjit03** [comment]
@Gauravjeetsingh is this something still valid or we can close this issue ?

**Comment by gurjit03** [comment]
@Gauravjeetsingh ?

**Comment by Gauravjeetsingh** [comment]
We can close this issue, https://github.com/KhalisFoundation/sttm-web/pull/1704 this PR fixed it.
