### ISSUE TITLE
Save pankti as favorite title

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1488]
Search for Shabad "bandhna har bandhna" and then favorite it. 
I would like it to save that **pankti** when i then go to view in list of favorite Shabads, rather than the heading of the Shabad.

If there is no line highlighted, bring up a prompt to the user to select the pankti from a dropdown to use as the bookmarked line.

**Comment by gurjit03** [comment]
@saintsoldierx can you please add the UI for this feature? So basically we need to store the pankti in the database when a user has decided to make that shabad a favorite?

**Comment by saintsoldierx** [comment]
@gurjit03 This needs to be fixed.

<img width="1115" alt="image" src="https://github.com/KhalisFoundation/sttm-web/assets/27791330/34ada994-774a-4fe6-ad02-62318e956f6d">

**Comment by saintsoldierx** [comment]
@gurjit03 can we fix this ASAP please
