### ISSUE TITLE
Issues with DEV & STG environments.

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1520]
We need to recreate or fix our deployment process. Currently, merges in GH are not auto deploying to Dev, Stg or production (master). We need it working as it was before. I am not knowledgeable on the finer technical details but in a nutshell: 

1. When we merge PR's, they should deploy to the correct branch. I believe what used to happen was it when we would merge, it would auto deploy to our dev environment (via heroku) and we would use dev.sikhiothemax.org to validate.
2. When we would merge to dev branch, stg.sikhitothemax.org would also get updated - I believe it was synch'd with dev, not entirely sure. 
3. Even master merges are not deploying to production. 
4. For every successful deployment, we would get notifications in #releases on our Slack channel eg. 
```

```
#stage - STTM-web - use-avm02 - Dev deployment started
1:25
#stage - STTM-web - use-avm02 - Complete - pm2  status online  - Installed Commit: 905918cb59eb6cc633862873a7bbb838a8be01bc - http://stg.sikhitothemax.org
1:25
#stage - STTM-web - euw-avm03 - Dev deployment started
:mega:
#stage - STTM-web - euw-avm03 - Complete - pm2  status online  - Installed Commit: 905918cb59eb6cc633862873a7bbb838a8be01bc - http://stg.sikhitothemax.org
```
```

However, this is no longer the case and we do not get any notifications.

I suggest to rebuild from ground up a new dev environment and document the process.

**Comment by saintsoldierx** [comment]
I need some clarification here.

What does heroku have to do with DEV and STG? From my understanding, previews of pull requests are done with heroku but DEV and STG are (supposed to be) deployed on Travis CI. @tsingh777 Is this a true statement do you know? @Gauravjeetsingh

**Comment by Gauravjeetsingh** [comment]
Veerji, dev deployment and PR previews were done on heroku. I am not sure about stg, never touched that. But the dev.sikhitothemax.org was hosted from the heroku app.
