### ISSUE TITLE
Shortcuts don't work after going full screen 

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1533]
In chrome, when you go full screen using shortcut (f), the other shortcuts no longer work. if you exit the full screen mode, the other shortcuts still no longer work.

**Comment by gurjit03** [comment]
@saintsoldierx do we still face this issue? Which shortcuts we are referring to here? What are the screens/pages/routes where we have faced this issue

**Comment by saintsoldierx** [comment]
Yes, so if i go on a page, click v (for vishraams) it shows vishraams. If i go full screen using F, then try V again for vishraams, it doesn't work.

**Comment by gurjit03** [comment]
@saintsoldierx I verified it is problem on macOS chrome only for now. Working on it currently.
