### ISSUE TITLE
Display Shabads by writer

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1547]
We need to be able to show a list of Shabads by a particular writer. So if I want to see all Baani by Guru Tegh Bahadur Jee, I should be able to easily search without entering a search term.

**Comment by gurjit03** [comment]
@saintsoldierx we need to have support from the API for the same

**Comment by gurjit03** [comment]
@saintsoldierx This feature is api-dependent so we can close this for now.
