### ISSUE TITLE
Add `ਦੋਹਰਾ ॥` before `ਸਾਧ ਅਸਾਧ ਜਾਨੋ ਨਹੀ ਬਾਦ ਸੁਬਾਦ ਬਿਬਾਦਿ ॥` in XL version of Rehraas Sahib 

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1587]
**Describe the bug**
Add `ਦੋਹਰਾ ॥` before `ਸਾਧ ਅਸਾਧ ਜਾਨੋ ਨਹੀ ਬਾਦ ਸੁਬਾਦ ਬਿਬਾਦਿ ॥` in XL version of Rehraas Sahib https://www.youtube.com/watch?v=Vb7FKvL4Ad4&t=1318s

**To Reproduce**
1. Go to https://www.sikhitothemax.org/sundar-gutka/raharaas-saahib
2. Click on `XL` version in the settings
3. Scroll down to `ਸਾਧ ਅਸਾਧ ਜਾਨੋ ਨਹੀ ਬਾਦ ਸੁਬਾਦ ਬਿਬਾਦਿ ॥`
4. See `ਦੋਹਰਾ ॥` is missing while it gets recited in https://www.youtube.com/watch?v=Vb7FKvL4Ad4&t=1318s

**Expected behavior**
Point 4 above

**Screenshots**
<img width="868" alt="image" src="https://user-images.githubusercontent.com/6245927/211332274-b4289018-f7b5-4415-aa79-9e37faf2db9e.png">

<img width="880" alt="image" src="https://user-images.githubusercontent.com/6245927/211336928-8de5a4e4-75f7-491d-b755-1f0bcc00ed80.png">

**Comment by gurjit03** [comment]
@saintsoldierx This feature is API-Dependent, so we can close it for now
