### ISSUE TITLE
That SSO page has a nice footer

&gt; Copyright © 2019 Khalis Foundation

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1600]
(Auto generated from slack)
That SSO page has a nice footer

&gt; Copyright © 2019 Khalis Foundation
https://khalis.slack.com/archives/CFRP8GWAD/p1674752204411349?thread_ts=1674745209.163269&cid=CFRP8GWAD

**Comment by MySmilingTurban** [comment]
Same issue in Copyright section in Terms of Service
