### ISSUE TITLE
Autoscroll speed issues.

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1609]
Autoscroll 1-50% works fine, but 51-100% seems to be same speed. Tested on latest version of Chrome on MacOS. Also, top speed should be faster.

**Comment by gurjit03** [comment]
@saintsoldierx surely we can improve the top speed here. Though there is no logic in controlling the speed when it crosses 50%. My immediate hunch suggests me that it's due to the browser implementation rather than the code. Still, I will test it and see if I can find something.

**Comment by gurjit03** [comment]
Closing this for now
