### ISSUE TITLE
Favorites improvements

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1610]
When a Shabad is favorited:
- Log date and time
- Allow a comment to be added as an option. _Use case: If someone wants to favorite a Shabad that they want to note as one they took from a Hukamnama or related to a special occassion_

**Comment by gurjit03** [comment]
@saintsoldierx Can you please add the UI for this feature? How/Where do we want to add this option?

**Comment by saintsoldierx** [comment]
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/27791330/221396591-bd59750c-7192-4ccf-9680-4872bb704674.png">
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/27791330/221396884-4ee9ef7b-65ac-47ab-a147-081e8edbdce2.png">
