### ISSUE TITLE
Title doesn't updates Ang when Ang is changed manually after search

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1614]
**Describe the bug**
When we search an Ang, open it, and open the next Ang, new Ang doesn't gets updated in Browser Title

**To Reproduce**
1. Open https://www.sikhitothemax.org/ang?source=G&ang=18
2. Open previous/next Ang by clicking previous/next button
3. Observe the page title on top (above site URL) still reads the previous Ang, 18, in this case,
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/6245927/220143576-26bc4890-b8a6-47a8-b69d-f56bc65103e4.png">

**Expected behavior**
The page title should reflect the correct Ang number.

**Comment by saintsoldierx** [comment]
I am unable to reproduce this. Works fine for me in Chrome/MacOS

**Comment by saintsoldierx** [comment]
Referring to the ang number in tab title for this issue.
