### ISSUE TITLE
Unwanted http-call while doing Sehaj Paath

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#1621]
**Describe the bug**
https://www.sikhitothemax.org/auth/jwt is made while loading an Ang from SGGS ji 

**To Reproduce**
1. Go to sttm.co
2. Click on `Ang [angnumber]` on the homepage (assuming you have last visited that Ang earlier; that is how we see that on the home page)
3. On the new page, see the unwanted http-call being made even when the user is not logged in

**Expected behavior**
https://www.sikhitothemax.org/auth/jwt should not be made in this case

**Screenshots**
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/6245927/222525728-1a71e24c-8fd1-4b66-b2d7-59615b6dba31.png">

**Comment by gurjit03** [comment]
Fixed
