### ISSUE TITLE
Verse is not saved in favorite shabads

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#1650]
**Describe the bug**
When we mark a shabad as fav, it doesn't save any verse id in the database, which results in all the shabads, showing the first verse in fav shabad page. 

When we mark the shabad as fav in the sttm-desktop app, it saves the verse id, but still doesn't show the verse in fav shabad page.

Sttm-web
![image](https://github.com/KhalisFoundation/sttm-web/assets/1990932/b006da5c-fa7d-4350-a5b2-7b5e979c5292)

Same account logged in sttm-desktop (it's not released in sttm-desktop yet, and currently in code review phase)
![image](https://github.com/KhalisFoundation/sttm-web/assets/1990932/5e9c8529-9e66-4116-9547-64d61d7d2dba)

**To Reproduce**
1. Go to any shabad
2. Click on star icon to mark as fav
3. Go to the favorite shabads page
4. You will see that it shows the first verse instead of highlighted verse

**Expected behavior**
It should save highlighted verse when marking as fav from sttm-web, and when retrieving favorite shabads, show the verse with saved verse id, instead of first verse.

**Comment by gurjit03** [comment]
@Gauravjeetsingh can you please recheck this now. I have already added feature to save pankti as favourite shabad title (https://github.com/KhalisFoundation/sttm-web/issues/1488).

**Comment by gurjit03** [comment]
Closing this as already fixed
