### ISSUE TITLE
Feature: download MP3 for any shabad

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#1693]
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/7478">7478</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Low</div>
                       <div> Freshdesk Ticket Description: </div><div dir="ltr">
<div>Is there a way to download the Listen to Shabad as MP3 for any shabad?</div>
</div>

**Comment by ManjotS** [comment]
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/7478">7478</a> for this issue.</div>

**Comment by saintsoldierx** [comment]
Closing - we are unable to offer downloads for the MP3s at this time at the request of Baru Sahib.
