### ISSUE TITLE
Mahaan Kosh Tooltip Inconsistencies

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#1699]
Mahaan Kosh tooltip is inconsistent. Sometimes it shows the title of word in yellow/orange, other times it doesn't. When you click on the word, it shows the title but then hover off the word and it shows the tooltip without the word title. It should always show the title. 

https://github.com/KhalisFoundation/sttm-web/assets/27791330/df8633f1-0c24-4685-b72a-50f1fc5a5478

**Comment by gurjit03** [comment]
@Gauravjeetsingh Let me know about how's its going ?

**Comment by Gauravjeetsingh** [comment]
@gurjit03 veerji, I haven't had a chance to work on this yet, got occupied with sttm-desktop release, if you have some bandwidth, you can take this one.

**Comment by gurjit03** [comment]
@Gauravjeetsingh I might not be able to start on this until some time ( next week maybe ). So feel free to start, just mention me here otherwise I will take it 👍🏻

**Comment by gurjit03** [comment]
@saintsoldierx Can you please review the dev once please. I have updated the mahankosh tooltip implementation.

**Comment by saintsoldierx** [comment]
@gurjit03 This looks good to me. I also think we need a setting to be able to turn this on/off.

**Comment by gurjit03** [comment]
@saintsoldierx yeah definitely agrees !
https://github.com/KhalisFoundation/sttm-web/issues/1706

**Comment by gurjit03** [comment]
@saintsoldierx Closing this one
