### ISSUE TITLE
Adds new menu option for turning on/off mahankosh tooltip

### ISSUE THREAD

**Issue by gurjit03** [KhalisFoundation/sttm-web#1706]
Needs a new option in the menu for turning on/off mahankosh tooltip

**Comment by JapnitS** [comment]
Working on this, PR is ready. Need to find the right icon for the Mahaan Kosh Tooltip setting.

**Comment by Gauravjeetsingh** [comment]
@JapnitS veerji, You would have to create a fork of this repo, and then push code in that fork, and create a PR here.

**Comment by JapnitS** [comment]
Feature added to the [release](https://github.com/KhalisFoundation/sttm-web/releases/tag/v1.17.9)
