### ISSUE TITLE
Mahaan Kosh Tooltip bug in Reading mode

### ISSUE THREAD

**Issue by JapnitS** [KhalisFoundation/sttm-web#1741]
**Describe the bug**
**Reading Mode**: The mahaan kosh tooltip does not translate the shabad at the mouse pointer but keeps displaying the same translated word for all. 

**To Reproduce**
1. Go to [sikhitothemax.org](https://www.sikhitothemax.org/)
2. Click on Reading mode in settings.
3. Try opening mahaan kosh tooltip by hovering/clicking on the word

**Expected behavior**
Mahaan kosh tooltip translates the word pointed at by the mouse

**Screenshots**
![Screenshot 2024-09-22 193133](https://github.com/user-attachments/assets/52a3b449-2481-4df5-a163-3712c7b054b4)

![Screenshot 2024-09-22 192700](https://github.com/user-attachments/assets/c2bdd90a-5540-47b0-af89-2b5e15ab6dd1)
![Screenshot 2024-09-22 192705](https://github.com/user-attachments/assets/62e6c315-b751-44a7-98fb-5d7ec0c1aa32)
![Screenshot 2024-09-22 192711](https://github.com/user-attachments/assets/dd18cd2a-e0c4-4e51-ac57-3fcb64ccdc52)
![Screenshot 2024-09-22 192805](https://github.com/user-attachments/assets/86974d29-b6d8-4591-964b-be68d6dcf86f)
![Screenshot 2024-09-22 192814](https://github.com/user-attachments/assets/fc2b3240-fd1c-4928-b083-97dc886b155e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome Version 128.0.6613.139 (Official Build) (64-bit), Edge Version 129.0.2792.52 (Official build) (64-bit)

**Smartphone (please complete the following information):**
 - Browser [

**Additional context**

**Comment by prebhdevsingh** [comment]
@JapnitS do you think this is something you can fix?

**Comment by JapnitS** [comment]
I will look into it ji @prebhdevsingh

**Comment by JapnitS** [comment]
Implemented in https://github.com/KhalisFoundation/sttm-web/releases/tag/v1.17.9
