### ISSUE TITLE
Add live search

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#198]
search once 3+ letters typed

**Comment by bogas04** [comment]
We need to make sure this is highly performant on mobile.

**Comment by saintsoldierx** [comment]
I believe this is live.

**Comment by saintsoldierx** [comment]
Sorry, this is not yet done.

**Comment by saintsoldierx** [comment]
Having discussed this with @Gauravjeetsingh, we decided to go with a google auto-suggest type function where search results appear as you type.
