### ISSUE TITLE
Have a way to announce new features 

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/sttm-web#204]
Ideas:
A single place in the header (e.g. bell icon) - easier and can go back to it even after dismissed
A dot on the element with new functionality - could prove be have greater visibility

Please share thoughts

**Comment by ManjotS** [comment]
agree. we need to add the icons in the top right we discussed. ie maryada, ll and other apps would go in an icon there too

**Comment by bogas04** [comment]
@saintsoldierx could you please make a mockup? Thanks a lot!

**Comment by bogas04** [comment]
We can create a new changelog page using [Github API](https://api.github.com/repos/KhalisFoundation/sttm-web/releases).

Next we can cache the previously known version somewhere and let user know in case of a version change.

Lastly, we can't just check it only on changelog page, so we would need to silently check it using latest release [API](https://api.github.com/repos/KhalisFoundation/sttm-web/releases/latest).

**Comment by ManjotS** [comment]
this is a 2 parter:

First is notifications like desktop (http://api.sikhitothemax.org/messages/desktop/) in our case it is http://api.sikhitothemax.org/messages/web/

Second is cookie driven like: 
![image](https://user-images.githubusercontent.com/644885/50196727-25744580-02f9-11e9-801a-a94fab21f631.png)

**Comment by saintsoldierx** [comment]
<img width="1679" alt="STTM-alert1" src="https://user-images.githubusercontent.com/27791330/59241808-f5c63c00-8bbd-11e9-88dd-1270bec9f82b.png">
<img width="1679" alt="STTM-alert2" src="https://user-images.githubusercontent.com/27791330/59241809-f5c63c00-8bbd-11e9-8979-89d44f38f828.png">
<img width="1679" alt="STTM-alert3" src="https://user-images.githubusercontent.com/27791330/59241810-f5c63c00-8bbd-11e9-876f-7bc612237a34.png">
 This is what I am thinking for the alert system which is high priority.

1. An alert slides in from top of the page regardless on what page the user is on. The user can dismiss the alert.
2. If the alert is dismissed, an alert icon should slowly flash on the page. If user clicks on the alert icon, the alert slides in from the top. 
3. Ideally, the icon would only appear IF the alert has been dismissed. This is just incase user clicks dismiss button before reading it properly or wants to re-read.

**Comment by ManjotS** [comment]
I'll get api work done on this.

**Comment by saintsoldierx** [comment]
@ManjotS make sure the way to add announcements is easy and quick too and allows for HTML markup so we can add links etc if needed.

**Comment by ManjotS** [comment]
It does allow for markup.. right  now for desktop we just use tablesplus to put messages into the db.

**Comment by ManjotS** [comment]
I've added the endpoint. Right now it displays a test message. You can access same as desktop via:

http://api.sikhitothemax.org/messages/web
http://api.sikhitothemax.org/messages/web/[date of last read message]

Before going to prod, the test message should be removed and a prod message should be added.

**Comment by Gauravjeetsingh** [comment]
@saintsoldierx Currently, we are using Toast notifications in sttm. We can add an alert with them as shown below:
![Screenshot from 2019-06-26 11-33-42](https://user-images.githubusercontent.com/1990932/60205560-597b7680-9806-11e9-9657-615d6c6c29c5.png)

Should I use this or do we want to create a separate design (full width on top) for alerts as in above mockup?

**Comment by ManjotS** [comment]
@saintsoldierx we still need the full implementation done

**Comment by saintsoldierx** [comment]
This has been implemented - will create new issue to track any enhancements.
