### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#207]
should match desktop and keep in step.

Arrow keys for prev/next

**Comment by bogas04** [comment]
Can you list down all possible keyboard shortcuts?

| Key | Action |
|:--|:--|
`/`| Focuses search field.
`⬇️`| Scrolls next line into view.
`⬆️`| Scrolls previous line into view.
`➡️`| Goes to next page/shabad.
`⬅️`| Goes to previous page/shabad.

**Comment by ManjotS** [comment]
@navdeepsinghkhalsa do we have a list for desktop? would like them to match

**Comment by navdeepsinghkhalsa** [comment]
Only differences are that desktop uses spacebar for going to main/searched line and hasn't implemented right/left for changing Shabad. Desktop maps left/up for previous line and right/down for next line

**Comment by saintsoldierx** [comment]
@maneetpaul do we have a list of keyboard shortcuts for Desktop?

**Comment by saintsoldierx** [comment]
Web will be slightly different but here are desktop shortcuts
**Mac**
Combination | Description
-- | --
CMD + 1 | Waheguru Slide
CMD + 2 | Mool Mantra Slide
CMD + 3 | Empty Slide
CMD + 4 | Anand Sahib (Bhog)
CMD + 5 | Help Guide
CMD + 6 | Shortcut Legend
CMD + / | Jump to search bar
CMD + G | Add Dhan slide or announcement
Spacebar (when in a shabad) | Switch between main line and unchecked line
Spacebar (when a special slide [ie waheguru slide, announcement, etc] is active) | Switch back to shabad

**Windows**
Combination | Description
-- | --
CTRL + 1 | Waheguru Slide
CTRL + 2 | Mool Mantra Slide
CTRL + 3 | Empty Slide
CTRL + 4 | Anand Sahib (Bhog)
CTRL + 5 | Help Guide
CTRL + 6 | Shortcut Legend
CTRL + / | Jump to search bar
CTRL + G | Add Dhan slide or announcement
Spacebar (when in a shabad) | Switch between main line and unchecked line
Spacebar (when a special slide [ie waheguru slide, announcement, etc] is active) | Switch back to shabad

Others:-
**MAC**
Combination | Description
-- | --
CMD + Q | Close app
CMD + U | Check for updates
CMD + H | Minimize window
CMD + M | Minimize window

**WINDOWS**
Combination | Description
-- | --
CTRL + Q | Close app
CTRL + U | Check for updates
CTRL + M | Minimize window

**Comment by AkalUstat** [comment]
@saintsoldierx i could take this on concurrently with #439

**Comment by AkalUstat** [comment]
@saintsoldierx do you want me to go off of the current desktop shortcuts or the newer ones that I am planning?

**Comment by saintsoldierx** [comment]
@AkalUstat i am happy to use current desktop shortcuts if that works.
