### ISSUE TITLE
Romanized search should be more accurate

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#208]
## What went wrong ?
current implementation of romanized search doesnt work well without 4-5 words

for example, search "sant"

## What should have happened instead ?
a fuzzy compare to the translit would be better

**Comment by bogas04** [comment]
Does this issue belong here or in BaniDB?

**Comment by ManjotS** [comment]
banidb

**Comment by bogas04** [comment]
We use soundex which is significantly better.
