### ISSUE TITLE
Add a developer/advanced mode with easter eggs

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#212]
use konami or some other code (ie typing 4/14/1699)

Start with the feature of including shabadid in the search drop down.

**Comment by bogas04** [comment]
How about `sat sri akaal`?

**Comment by saintsoldierx** [comment]
@ManjotS can you give me more information on this? More details of what you're looking for?

**Comment by gurjit03** [comment]
@saintsoldierx Not sure about this feature ! How should we proceed further with this one ?

**Comment by gurjit03** [comment]
@saintsoldierx I am closing this ticket for now. We can reopen this ticket when we have some more description
