### ISSUE TITLE
Add phonetic first letters (romanized)

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#224]
Phonetic First letters should work like:

ttbmjk

finds

ਤੂ ਠਾਕੁਰੋ ਬੈਰਾਗਰੋ ਮੈ ਜੇਹੀ ਘਣ ਚੇਰੀ ਰਾਮ॥

**Comment by saintsoldierx** [comment]
Do you have some mapping for letters? like t can equal ਤ or ਠ, is there a mapping for all 35 u have? @ManjotS

**Comment by ManjotS** [comment]
We already have this feature. This is what romanized search does. We can do
a version that removes the space requirement.

**Comment by saintsoldierx** [comment]
@ManjotS romanized search currently is by word. We dont have first letter search phonetic right?

**Comment by ManjotS** [comment]
search type 7 seems to do this

**Comment by ManjotS** [comment]
confirmation: https://api.banidb.com/v2/search/ttbmj?source=all&searchtype=7&page=1

**Comment by ManjotS** [comment]
The limitation here is that web is not allowing this to work because it expects x words (Which we should keep).

Web should create its own new search type for first letter english that uses searchtype 7 as well but allows passing letters only (and should enforce minimum 3-4 characters).

**Comment by ManjotS** [comment]
@bickyb tagging you here to track
