### ISSUE TITLE
Add amrit keertan index

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#24]
http://sikhitothemax.com/akindex.asp

Should be in DB

**Comment by bogas04** [comment]
Is this still relevant ? @ManjotS

**Comment by ManjotS** [comment]
yes

**Comment by tarunsingh5** [comment]
@ManjotS why do we still need this?

**Comment by bogas04** [comment]
I'm closing this as it concerns `banidb`. Once its API supports Amrit Keertan Index, we'll add it here.

**Comment by ManjotS** [comment]
its still a web feature we want at some point, it should be in API following next hackathon

**Comment by navdeepsinghkhalsa** [comment]
This fell off the radar as it wasn't on the spec list for V2. I'll add it and include it in the release

**Comment by bogas04** [comment]
@saintsoldierx we're blocked until API is ready then.

**Comment by pdvsingh** [comment]
Is the API ready for this? @ManjotS

**Comment by ManjotS** [comment]
no

**Comment by saintsoldierx** [comment]
API ready for this yet @ManjotS ? Can we get an update, this ticket been open for over 3 years.
