### ISSUE TITLE
Regression: js, css and images no longer utilizing s3

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#247]
## What went wrong ?
js css and images are loading from relative paths and not s3

## What should have happened instead ?
use s3 to speed things up as we did originally

**Comment by ManjotS** [comment]
@bogas04 in the master deploy script we could do an aws s3 upload command and then replace asset strings with full urls. 

What do you need to make that happen?

**Comment by bogas04** [comment]
We can do this in webpack now. Can you tell me what exactly is the issue?

**Comment by ManjotS** [comment]
https://s3-us-west-2.amazonaws.com/sttm/website/

css/
fonts/
images/
js/
etc...

deployment needs to run `aws s3 cp .* s3://sttm/website/`

**Comment by bogas04** [comment]
Closing as we're on azure CDN now.
