### ISSUE TITLE
Add reset button to font and display options

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#248]
should reset options to default

**Comment by bogas04** [comment]
Do you want a per setting reset button or just one big reset button?

**Comment by ManjotS** [comment]
originally was thinking one reset button per pane

**Comment by bogas04** [comment]
To implement this we just need to add a new action to redux which sets the values to their defaults (present in constants file). And then add Reset button and map onClick of it to this redux action.

I can mentor with this.

**Comment by ManjotS** [comment]
Maybe add it as last option in each panel .
