### ISSUE TITLE
Add Search tools

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-web#252]
Add search tool functionality

**Comment by bogas04** [comment]
Could you please describe it better? 

Is this an extension of #319 ?

**Comment by ManjotS** [comment]
No, this is like google search tools, the ability to sort by shabad,ang,writer,raag,source,etc would be the first option.

https://support.google.com/websearch/answer/142143?hl=en

**Comment by bogas04** [comment]
Are we blocked by BaniDB on this? Is the API exposed? @navdeepsinghkhalsa

**Comment by navdeepsinghkhalsa** [comment]
I don't think there's ticket for this in the API repo

**Comment by ManjotS** [comment]
@saintsoldierx assigning this to you. please define and assign api changes as needed

**Comment by saintsoldierx** [comment]
For this ticket, we will add raag & writer

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/82986052-fc55eb00-9fa9-11ea-8890-609f8ae894cd.png)

**Comment by saintsoldierx** [comment]
So here's breakdown of the search tools @gurjit03 :-

- If i begin to filter down, it should not remove inactive filters. So let's say if i filter source by SGGSJ, writers should highlight all 6 Gurus, Bhagats, Farids etc, but other writers, such as the other 4 Gurus, should not disappear. Instead, make bold those that are active and have results, leave normal weight of text for inactive.

**Comment by saintsoldierx** [comment]
- An "apply" button next to filter may be best too.

**Comment by saintsoldierx** [comment]
We have writer, just need to add raag.

**Comment by gurjit03** [comment]
@saintsoldierx we are dependent on API for this.

**Comment by gurjit03** [comment]
@saintsoldierx we are blocked by API for this. So closing this for now
