### ISSUE TITLE
Increase shadow on horizontal scroll for display controls

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#269]
<img width="400" alt="screen shot 2018-01-30 at 1 34 43 pm" src="https://user-images.githubusercontent.com/6177621/35554610-5accbc42-05c2-11e8-947e-956c7cd7b773.png">

**Comment by plug-n-play** [comment]
@ManjotS / @bogas04 - Please suggest if this is what we want ?

https://codepen.io/amandeep/pen/zjZGNd

**Comment by bogas04** [comment]
@plug-n-play Thank you so much for your contribution! I think we need shadow on horizontal scroll part (as you can see near "Assist" of original screenshot.

**Comment by plug-n-play** [comment]
@ManjotS @bogas04 @saintsoldierx @tarunsingh5 I believe this is for mobile-view where all options are not fully visible

![image](https://user-images.githubusercontent.com/6245927/39471944-a62fbe1c-4d63-11e8-8729-d3ce5b90eb3f.png)

Somehow I feel that a shadow may not be right candidate here - thought?

**Comment by plug-n-play** [comment]
Is that how we want this @ManjotS @bogas04 @saintsoldierx @tarunsingh5 ?

![image](https://user-images.githubusercontent.com/6245927/39764904-3ba24b96-52fe-11e8-87f9-bbca17aa97b6.png)

**Comment by saintsoldierx** [comment]
@plug-n-play can you still help with this? I think maybe in mobile we should remove the text and just have the icons?

**Comment by bogas04** [comment]
I like that idea.

![www sikhitothemax org_search_q mmkg type 1 source all](https://user-images.githubusercontent.com/6177621/50052607-91fe1180-014c-11e9-8b0b-63d9079cd3d0.png)
