### ISSUE TITLE
Add steps to larivaar assist (subtle to drastic)

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#295]
make the learner button into a drop down with 1-5. Each number if a slightly more subtle color.

1 is bright orange, 5 is very subtle and you almost can't see the color difference. 1 is default.

**Comment by bogas04** [comment]
Do we really need this? What difference does it make if the color difference is subtle or drastic, it'll still be perceived.

**Comment by ManjotS** [comment]
it allows people to slowly phase it out .. ie subtle would be almost black where you cant notice it

**Comment by saintsoldierx** [comment]
@AkalUstat you want to take a crack at this? In advanced, add a setting IF larivaar mode assist is on to change the strength of the colors from 1-5...

**Comment by AkalUstat** [comment]
sure
