### ISSUE TITLE
Click to see all Bani by writer - similar to how Pannaa works

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#319]
Please select which platform you are using:-
Desktop Version

Feedback Type
Enhancements

What went wrong?
Sat Sri Akal, it would be great if i can search for each Guru's bani, so if i click Guru Arjan Dev ji, all the bani from Him appears. Or Guru Nanak Dev ji, and just those verses appear, Or Kabir. If that is possible, woudl be greatly appreciated. thanks
 
What should have happened instead?

    
How can the issue be recreated by our team?
i cannot search as above, on any specific GURU or BHAGAT's bani

Which web browser are using?
 

Operating System

Name
sharan kaur

**Comment by ManjotS** [comment]
This is a drop down imo similar to source - maybe first drop down has "search by writer" and then input text turns into drop down?

**Comment by bogas04** [comment]
Does the API support it? Just wanted to know whether we're blocked by it or not.

Your suggestion seems great. An autocomplete drop-down for search by writer.

**Comment by ManjotS** [comment]
you are blocked by API

**Comment by saintsoldierx** [comment]
Tracking in https://github.com/KhalisFoundation/sttm-web/issues/252
