### ISSUE TITLE
Add server rendering

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#329]
Now that we're on react and have isomorphic rendering code, we can go ahead and server render our pages. We'll get a lot of benefits like:

* Faster meaningful paint.
* Stream HTML.
* Add better meta tags and SEO related details. #317 

How to do it?

* [ ] Add `node-fetch` to load details on server end, this is required for SEO and rendering content on search/shabad pages.
* [x] Use templating, `marinate` probably to generate different HTMLs per route.
* [ ] Figure out server rendering (use `require()` in-place of `import()`)

**Comment by saintsoldierx** [comment]
@bogas04 is this completed?

**Comment by saintsoldierx** [comment]
Navdeep, Gurpreet - what's your thoughts on this ticket. 2-3 years old now, is this still valid?

**Comment by gsin11** [comment]
I can check this out, idea is good and definitely in favour of better SEO performance.

**Comment by navdeepsingh** [comment]
@saintsoldierx For SSR purpose (https://github.com/KhalisFoundation/sttm-web/issues/375#issuecomment-641609314) @plug-n-play already working on it. We need to chalk out beforehand rather we opt for the Nextjs method or manually using marinate, webpack, etc.
cc @gsin11

**Comment by navdeepsingh** [comment]
As this confirmed, we need to work towards: "it's better we add webpack+babel tooling for our server to be able to render react components". @gsin11 we can sync together to make it possible.

**Comment by saintsoldierx** [comment]
@gurjit03 i want you take this up soon as well please. Get with Navdeep/Gurpreet to learn more about it.

**Comment by gurjit03** [comment]
@saintsoldierx we can close this as our direction is more towards next.js now.
