### ISSUE TITLE
Ditch floats and col-* in favour of flex and CSS grid

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#352]
It's time.

* SearchBar
* Header

![image](https://user-images.githubusercontent.com/6177621/37921287-fff4a9a0-3146-11e8-92c9-534bb20a7db9.png)

**Comment by saintsoldierx** [comment]
Not sure if this has been done or already.

**Comment by navdeepsingh** [comment]
Yeah! It's already done. For layout, we used Flex & Grid only.
