### ISSUE TITLE
AutoFocus causes page to jump up on mobile

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#360]
## What went wrong ?

Logo jumps up on page load

## What should have happened instead ?

It should have stayed there

## How can authors of this project cause the issue to occur on their systems ?

  1. Load the home page from mobile
  2. Observe logo moving up by few pixels as the keyboard on mobile comes up.
 
## What were you trying the project on ?

  - Browser: chrome
  - Browser Version: 65
  - Operating System: Android

**Comment by bogas04** [comment]
We need to make the search for positioned as absolute.

**Comment by tarunsingh5** [comment]
is this still an issue @bogas04

**Comment by saintsoldierx** [comment]
Unable to replicate, looks good on mobile. No issues.
