### ISSUE TITLE
In case of an error, no links work.

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#365]
## What went wrong ?

If something breaks, no links work.

## What should have happened instead ?

Links should work.

## How can authors of this project cause the issue to occur on their systems ?

  1. Trigger an error (Add react dev tool ext to chrome, search for "Fetch", change error: null to "true").
  2. Click any link (logo/hukamnama etc.)

## What were you trying the project on ?

  - Browser: Chrome
  - Browser Version: 66
  - Operating System: OSX

**Comment by rajkambo** [comment]
After digging into the problem with the GenericError being rendered in Root.js in #473 it looks like we need to redesign how errors are handled in the app. The problem really starts with this attempt at a "catch all" GenericError: https://github.com/KhalisFoundation/sttm-web/blob/master/src/js/Root.js#L29. What happens is the error page gets rendered correctly, but the Routes don't get set up. So after rendering the error, any subsequent clicks don't do anything. 

I read this great article: https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html, and took a similar approach in #473. In this case, any error related to searching never propagates up to the Root.js so all the Routes remain in place after the GenericError has been rendered.

So IMO what we need to do is create a generic "HandleGenericError" component, and have it wrap everything that gets returned in the render calls of all the route specific page's index.js's (e.g. what was done in the Search/index.js here: https://github.com/KhalisFoundation/sttm-web/blob/47435e056677933dde9afb170c5b2cb5abb303e8/src/js/pages/Search/index.js#L39)

**Comment by bogas04** [comment]
@rajkambo I love your debugging style.

Sorry I couldn't help you out before. So problem is that we are catching errors at a level above Router, and `<Links />` have no idea what to do without `<Router />`. Secondly, we always render error based on state, but never update it.


I've moved the `componentDidCatch` at Layout level, coz that's something we always render for each route.

**Comment by rajkambo** [comment]
@bogas04 looks great! thanks for the detail! 👍 And no problem :D So long as the team gets the job done, it's all good :D
