### ISSUE TITLE
URL Shortner should accept highlighted tukk id

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#366]
## What went wrong ?

If you reach a Shabad page with Highlighted tukk set to some ID, create short URL for it doesn't consider it.

## What should have happened instead ?

Highlighted tukk should be shown even for shortened URLs.

## How can authors of this project cause the issue to occur on their systems ?

  1. Open [this shabad](https://www.sikhitothemax.org/shabad?id=2812&q=lrpm&&&source=all&highlight=31520).
  2. Click copy button in top share bar.
  3. Visit the copied URL, highlighted tukk isn't highlighted. 

## What were you trying the project on ?

  - Browser:
  - Browser Version:
  - Operating System:

**Comment by bogas04** [comment]
@navdeepsinghkhalsa what would be required to enable this? basically 

`https://sttm.co/s/{id}/{h}` ➡️ `https://www.sikhitothemax.org/shabad?id={id}&highlight={h}`

**Comment by tarunsingh5** [comment]
fixed
