### ISSUE TITLE
Help: Add a section explaining how to use do ang-by-ang paath of granths.

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#367]
## What went wrong ?

Someone on [Reddit](https://www.reddit.com/r/Sikh/comments/87bur8/sikhitothemax_just_had_a_major_rewrite_making_it/dweoci9/) asked me about this, apparently it isn't quite intuitive.

**Comment by tarunsingh5** [comment]
@maneetpaul can you write this one up?

**Comment by saintsoldierx** [comment]
@maneetpaul it's all you 👍

**Comment by saintsoldierx** [comment]
Done. https://support.khalisfoundation.org/support/solutions/articles/63000262698-how-do-i-search-via-ang-page-
