### ISSUE TITLE
Improve Index Page

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#389]
Now that we've index page, let's add more stuff to it:

* [x] Add vaars in SGGS.
* [ ] Bhai Gurdaas Jee's index.
* [ ] Add author wise indices. #35

**Comment by bogas04** [comment]
We simply need to populate this JSON

https://github.com/KhalisFoundation/SikhiToTheMax-Web/blob/dev/src/js/pages/GranthIndex/raagIndices.js#L1-L4

**Comment by bogas04** [comment]
We should also add description of the Granths and chapters. For an outsider, this would probably be the entry point, and educating right here would be ideal. Also good for SEO.

**Comment by yudhv** [comment]
Can I take this up?

**Comment by prebhdevsingh** [comment]
@yudhv veer ji, that would be great.

**Comment by prebhdevsingh** [comment]
@yudhv would love to get you on the Khalis slack. https://khalis.slack.com/

**Comment by saintsoldierx** [comment]
@yudhv are you working on this?

**Comment by yudhv** [comment]
Oh, sorry. I had forgotten about this. I can work on this. If someone else wants to take it up, I'm OK with that too.... @saintsoldierx

**Comment by saintsoldierx** [comment]
No worries @yudhv , yes would love you to work on it. 

@ManjotS this is an older ticket - could you update any requirements if needed.

**Comment by ManjotS** [comment]
We can start with tasks listed in OP, Dasam Granth can be an addition as well. (Bhaags and Raags)

**Comment by AkalUstat** [comment]
@saintsoldierx I can take this up

**Comment by saintsoldierx** [comment]
@Gauravjeetsingh please update with your questions for Manjot Singh

**Comment by yudhv** [comment]
Hey everyone. Sorry for taking up so much time. I only started working on this a couple of weeks back. The only meaningful change worth picking from the work I did is the raag indices object where I added descriptions for each raag. Mostly used data from the SikhWiki, jawadditaksal, and some personal opinions after listening to the shabads from some of the raags. Here is the file: https://github.com/yudhv/sttm-web/blob/yudhv/Index/src/js/pages/GranthIndex/raagIndices.js

Feel free to use if as you see fit.

**Comment by saintsoldierx** [comment]
@yudhv thank you! Let us know if you make progress. I will keep this assigned to our other devs if they get to it first else would love to see any progress you may have made in meantime. Thanks

**Comment by yudhv** [comment]
@saintsoldierx Thank you. I'll aim for the next couple of weeks to have the PR ready.

**Comment by yudhv** [comment]
> We should also add description of the Granths and chapters. For an outsider, this would probably be the entry point, and educating right here would be ideal. Also good for SEO.

Here is the PR for the Granth description and description for the Raags - #1167
