### ISSUE TITLE
Make searching more intuitive 

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#406]
Please select which platform you are using:-
Desktop Version

Feedback Type
shabad not found

What went wrong?
wjkk wjkf jio I can't seem to find "lakhi jangal khalsa aye deedar" any idea how and where to find that shabadpls add all shabads for easy search tq
 
What should have happened instead?
it is in amrit kirtan but results don't show
    
How can the issue be recreated by our team?
tell me what must I use to search it

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
morgan singh

**Comment by bogas04** [comment]
Our can't find Shabad page does direct to help page to learn about searching. What else can we do to improve this? I know it's not intuitive for newcomers.

@tarunsingh

**Comment by bogas04** [comment]
@ManjotS @navdeepsinghkhalsa

**Comment by tarunsingh5** [comment]
This is due to us not having sarabloh granth shabads in @manjots the Amrit
kirtan work I spoke to you about should resolve this

**Comment by saintsoldierx** [comment]
We have it :)
