### ISSUE TITLE
Error screen on Safari

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#408]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
I visited on my iphone 6 the website yesterday (random shabad) and opened the browser today. It gave an error screen.
 
What should have happened instead?
Reloaded same shabad from yesterday 
    
How can the issue be recreated by our team?
Open and do same steps on iphone 6

Which web browser are using?
Safari 

Operating System
Other

Name
Yatin Sharma

**Comment by bogas04** [comment]
Can somebody with iPhone test this? @ManjotS @tarunsingh5

**Comment by taranjs** [comment]
Tried on iPhone 6S but unable to reproduce. Works like a charm!

**Comment by bogas04** [comment]
Hi @taranjs , thank you so much for verifying.

Would you like to contribute to the project?

**Comment by taranjs** [comment]
Yes! You can add me as a collaborator! I already cloned the repo and looking around the code and current open bugs.

**Comment by bogas04** [comment]
Very good jee.

You can check the README of the project, it has a lot of details and even a video walkthrough of app and codebase.

Next up, you can take up any of the [https://github.com/KhalisFoundation/SikhiToTheMax-Web/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22%F0%9F%91%B6+good-first-pr%22 ](good-first-pr) issues or complex ones if you like. Just assign yourself to it :D
