### ISSUE TITLE
User profiles to save display preferences and more

### ISSUE THREAD

**Issue by irvanjitsingh** [KhalisFoundation/sttm-web#415]
Implement user authentication (facebook/email/openid, etc) and profiles. Can then allow users to save and curate favourites lists, search history, etc.

**Comment by bogas04** [comment]
Firebase would be cool here.

**Comment by ManjotS** [comment]
This should utilize khalis auth first and foremost but fb/google to authenticate as well

**Comment by ManjotS** [comment]
fyi khalis auth documentation is on bitbucket

**Comment by ManjotS** [comment]
new khalis auth SSO is completed and can be used.

**Comment by saintsoldierx** [comment]
@saintsoldierx to create some initial use cases

**Comment by saintsoldierx** [comment]
For the first phase, I would like to have ability to save favorite Shabads and display preferences.

![image](https://user-images.githubusercontent.com/27791330/93656979-5b20f380-f9e3-11ea-8813-b6886e65f557.png)

![image](https://user-images.githubusercontent.com/27791330/93657014-958a9080-f9e3-11ea-96b9-a0f5fa4b54e8.png)

- A icon of user will appear in top right corner. Clicking on it will give them option "My Favorites" and "Profile" where user can change their icon, password(?), and any other things related to their profile. 
- The * icon will only appear if user logged in.

**Comment by gurjit03** [comment]
@saintsoldierx We can close this issue as it's implemented
