### ISSUE TITLE
Add Steeks and Bishraams to display options

### ISSUE THREAD

**Issue by irvanjitsingh** [KhalisFoundation/sttm-web#416]
Self-explanitory.

**Comment by bogas04** [comment]
Blocked by BaniDB?

**Comment by tarunsingh5** [comment]
@ManjotS @saintsoldierx - should we revisit

**Comment by saintsoldierx** [comment]
We already have multiple visraam options.

**Comment by tarunsingh5** [comment]
we should have fareedkot teeka, manmohan singh, sant singh, etc

**Comment by saintsoldierx** [comment]
I believe we have VISHRAAM source already. Just need to add STEEKS option.

**Comment by ManjotS** [comment]
guys these are just translations json from the API and api already has them.
