### ISSUE TITLE
Allow changing font size of translations and transliterations

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#439]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
When making the font bigger only the Gurbani size changes
 
What should have happened instead?
There should be a slider for all the fonts or the one  should change all of them 
    
How can the issue be recreated by our team?
Use the slider under "font"

Which web browser are using?
Internet Explorer 

Operating System
Microsoft Windows

Name
Gurvir Chatra

**Comment by AkalUstat** [comment]
@saintsoldierx i can attempt this

**Comment by AkalUstat** [comment]
any specific design thing @saintsoldierx

**Comment by saintsoldierx** [comment]
No, just keep to current standards (padding, spacing, colors etc)

**Comment by saintsoldierx** [comment]
@AkalUstat can you work on this one too for this month?

**Comment by Gauravjeetsingh** [comment]
Keeping this open for now. Currently, translation and transliteration font size has no separate control. It just decreases in the given ration with same slider.

**Comment by saintsoldierx** [comment]
Add a drop down for translit, translation and teeka under advanced settings panel for now please. @Gauravjeetsingh
