### ISSUE TITLE
Mobile Issue. Broken Matra in Lariwar Assist view

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#448]
![image](https://user-images.githubusercontent.com/6245927/39765925-9dc58520-5300-11e8-8fef-b88b0ccd44d9.png)

Please observe Sihari is broken. The last Shabad should appear only when it is complete, else should follow in next line.

@bogas04 @ManjotS @saintsoldierx

**Comment by bogas04** [comment]
@harpreetkhalsagtbit please share the update when you find time :) Feel free to ask any question you've!

**Comment by harpreetkhalsagtbit** [comment]
@bogas04 
I did some fixes please review code and go through the comment to understand the problems fixed, whats remaining, why this solution and let me know your thoughts on all of these.

If you like what have been done till now - then 60% work is done. Remaining is some more complex character combination.

Larivaar color highlight is broken as of now, will definitely fix.

To test - please uncheck - 
```css
.display .gurbani-display div.larivaar {
    word-break: break-all;
}
```
