### ISSUE TITLE
Remove English translation from Header

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#449]
![image](https://user-images.githubusercontent.com/6245927/39766207-5c6c38b6-5301-11e8-9861-bb89cbf45bac.png)

Please observe it is currently not possible to remove English Translation from Shabad header in Search view

@ManjotS @bogas04 @saintsoldierx

**Comment by bogas04** [comment]
[Meta component](https://github.com/KhalisFoundation/SikhiToTheMax-Web/blob/dev/src/js/components/Meta.js#L53-L94) handles this, we need to pass the prop of options from [ShabadContent](https://github.com/KhalisFoundation/SikhiToTheMax-Web/blob/dev/src/js/components/ShabadContent.js#L81) down to Meta.

**Comment by bogas04** [comment]
@tarunsingh5 @ManjotS  when should we hide english? When english translation is off or transliteration is off? Today we have limited languages in both transliteration (english) and translation (punjabi, spanish, english), but as we add more languages, we would want to update header based on which option? 

@plug-n-play as discussed, let's hide English when both `transliterationLanguages` and `translationLanguages` don't contain `"english"` for now.

**Comment by ManjotS** [comment]
If anything english (transit or translation) is shown, show it in header.

Then we can do same with other languages

**Comment by bogas04** [comment]
```js
const shouldShowEnglishInHeader = translationLanguages.includes('english') || transliterationLanguages.includes('english')
```
