### ISSUE TITLE
Hukamnama not scraped entirely

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-web#45]
entire hukamnama is not displaying on STTM.org website

http://sikhitothemax.org/hukamnama.php

**Comment by prebhdevsingh** [comment]
For hukamnamas in particular, if hukam is salok, we need to bring in the pauri as well.

" If the scriptural composition that is continuing on the top of the left hand Ang is a vaar (ode) then start from the first of the saloks preceding the pauri and read upto the end of the pauri. Conclude the reading at the end of the Hymn with the line in which the name ‘Nanak’ occurs."

Also good to support these variations in future: http://www.gurmatbibek.com/contents.php?id=459

**Comment by ManjotS** [comment]
The way I would solve this is with the shabad ids above 5000000.. basically create shabads for the full shaka.

**Comment by ManjotS** [comment]
@tarunsingh5 we need a plan on this at some point

**Comment by tarunsingh5** [comment]
@ManjotS i think we may need to create a Hukamnama Index - it's doable

**Comment by saintsoldierx** [comment]
@ManjotS @tarunsingh5 who can take this on?

**Comment by ManjotS** [comment]
Navdeep Singh is with api 2

**Comment by saintsoldierx** [comment]
This is still an issue

**Comment by Gauravjeetsingh** [comment]
Fixed in #702
