### ISSUE TITLE
Map SikhNet shabadid to BaniDB ids

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#452]
Please select which platform you are using:-
Desktop Version

Feedback Type
Page says something went wrong

What went wrong?
https://www.sikhitothemax.org/shabad?id=20021
Does not return a shabad.Correction
 
What should have happened instead?
A shabad associated relieving ANXIETY does not return the shabad.
    
How can the issue be recreated by our team?
Click on Anxiety on this page https://www.sikhitothemax.org/shabad?id=20021

Which web browser are using?
Chrome don't know

Operating System
Microsoft Windows

Name
Cathy Palasz

**Comment by bogas04** [comment]
@ManjotS do you know what's wrong here?

**Comment by ManjotS** [comment]
We need their actual source link.. that shabad id doesnt exist

**Comment by ManjotS** [comment]
it was chatar chakr vartee according to sikhnet searches..

**Comment by bogas04** [comment]
@ManjotS What should be done? A manual redirect? Maybe we can add a service that checks on Sikhnet?

**Comment by tarunsingh5** [comment]
we should tell gurmustak to update sikhnet links

**Comment by bogas04** [comment]
@saintsoldierx closing this in favour of https://github.com/KhalisFoundation/BaniDB-API/issues/47
