### ISSUE TITLE
REGRESSION: input requirements only forced on first page

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#459]
**Describe the bug**
do a search, then in the top type only 1 or 2 characters and do a first letter search. It works. 

**Expected behavior**
input requirements should be enforced

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF

**Comment by ManjotS** [comment]
sorry try putting in less than 4 words in romanized search .. it doesn’t
enforce

**Comment by Gauravjeetsingh** [comment]
@ManjotS Currently, we show an error if we have less than two words in the romanized search. With #750 this validation will now work on the search page as well.

But do I need to limit it to 4 words? 
cc: @saintsoldierx

**Comment by ManjotS** [comment]
for spicy?

**Comment by Gauravjeetsingh** [comment]
Yeah, for spicy.

**Comment by ManjotS** [comment]
the algorithm needs 4 I think.

**Comment by Gauravjeetsingh** [comment]
It's fixed in production now. Closing it.
