### ISSUE TITLE
Save hukamnama everyday and provide ability to open hukam from a certain date

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-web#46]
We should save the shabad ID of the hukamnama in a table and provide ability to look up a hukamnama by entering a date.

**Comment by navdeepsinghkhalsa** [comment]
Great idea! Hukamnama is already saved by Khajana API. Will add functionality to Khajana to call previous dates and to STTM website to find them

**Comment by bogas04** [comment]
@navdeepsinghkhalsa  do you know if there's an API to get hukamnama by date ?
