### ISSUE TITLE
Search via first letters of Romanized Gurmukhi

### ISSUE THREAD

**Issue by bickyb** [KhalisFoundation/sttm-web#461]
So say for example you want to search for the shabad `Jo Mange Thakur Apne Thay`. You would need to know the exact spelling of the romanized shabad to be able to find it. What would be more effective is if we can search for the first letters: `jmtat` . This is the functionality that was available in sikhitothemax the original . Also, we need the ability to search phonetically. So say for example I am searching for the shabad Kar `Kirpa Prabh Dheen Dhayala`. Then I should be able to search for either ‘KKPDD’ or ‘CCPTT’ as these are phonetically close in English. This was doable in the original sikhitothemax. Please let me know if you have any questions and I can walk you through the needed functionality on a phone call if needed.

**Comment by bogas04** [comment]
@ManjotS @navdeepsinghkhalsa

**Comment by bickyb** [comment]
The current first letter search is Gurmukhi based.  We would like to search via first letter of Romanized text with phonetics. Currently, when I type jmt, the Gurmukhi keyboard is used.

**Comment by ManjotS** [comment]
we need to add a new search type to api

**Comment by bickyb** [comment]
Gur Fateh,
I wanted to see if you have been able to add this functionality to the SikhiToTheMax app.  Please let me know if you need to beta test or provide feedback.

**Comment by ManjotS** [comment]
Closing in favor of #224 (duplicate)
