### ISSUE TITLE
Unable to type anything in the Search area after following these steps

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#463]
Use is unable to write anything in the search area after following these steps:

1. Search: “sksls”
2. Click "Panna 12"
3. Observe that we are unable to type anything in the search box now.
4. This is not a blocker, since user can go back to Home Page, where search starts working again

**Comment by bogas04** [comment]
The reason is that you're moved to "Ang" type, and can only type numbers.

I guess we can give an indication to user that they need to change their search type.

**Comment by bogas04** [comment]
@saintsoldierx what do you suggest?

**Comment by saintsoldierx** [comment]
Maybe (for now) just a message that pops up when a user enters anything other than a number to say "You are searching by ang and must select numbers only" or something to that effect?

**Comment by bogas04** [comment]
It's not really possible to show it without using alert/etc. So I'm closing it for now.
