### ISSUE TITLE
Font-Size Change functionality is not smooth

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#464]
Font size flickers unexpectedly when trying to change it (It isn't a smooth experience/transition)

**Comment by plug-n-play** [comment]
This might be a good solution - Instead of slider, lets have 2 icons - Small size and Big size - Tapping the respective icon performs what is expecting

@saintsoldierx  - thoughts?

**Comment by plug-n-play** [comment]
![image](https://user-images.githubusercontent.com/6245927/40216095-122e0ee0-5a82-11e8-9a59-1be20a11341f.png)

**Comment by saintsoldierx** [comment]
I am not too keen on just having two icons. I do like the slider - but can it be incremental rather than smooth? Would this solve the issue? @bogas04 

![image](https://user-images.githubusercontent.com/27791330/40255009-6d2e3280-5a9a-11e8-8039-2c87476c070b.png)

**Comment by saintsoldierx** [comment]
@plug-n-play what do you think of the above?

**Comment by plug-n-play** [comment]
@saintsoldierx - Sorry for the super late reply.

This is good. Recommend to keep only this portion with a small adjustment:
![image](https://user-images.githubusercontent.com/6245927/57476553-7b4f8700-72b4-11e9-92b0-fd7440d4a1aa.png)

Also, we should limit the smallest permissible font. It currently goes as small as this:
![image](https://user-images.githubusercontent.com/6245927/57476617-9ae6af80-72b4-11e9-9cf2-5f254b30e263.png)

**Comment by saintsoldierx** [comment]
@plug-n-play this is one of the most annoying bugs on the UI side of things - something you could fix?

**Comment by tarunsingh5** [comment]
i think this is stale - @saintsoldierx should we close?

**Comment by plug-n-play** [comment]
Closing this as we now how new controls
