### ISSUE TITLE
Ability to disable cartoonified 404 pages

### ISSUE THREAD

**Issue by taranjs** [KhalisFoundation/sttm-web#466]
While the cool cartoons on 404 pages are awesome, they might not be the best experience when presenting to loads of live sangat in the Gurdwara Sahib.

Eg. this page
https://www.sikhitothemax.org/search?q=random

The user should have ability to turn them off because it is very common to have typo and land on these pages, which could be distracting for the sangat.

**Comment by plug-n-play** [comment]
@ManjotS @saintsoldierx @bogas04 @navdeepsinghkhalsa @taranjs - shall we remove this altogether or still keep it with setting option?

**Comment by ManjotS** [comment]
we want to keep it. We are discussing options, but for now can consider
removing from results page. We are thinking to add more characters.

We can make an option to turn it off everywhere for sure.

**Comment by plug-n-play** [comment]
or possibly have an image like this:
![image](https://user-images.githubusercontent.com/6245927/40254687-0515e6ee-5b02-11e8-8816-7ac68ed754f7.png)

**Comment by saintsoldierx** [comment]
The cartoons are a little quirky - but i like them. They just need improving.

**Comment by gurjit03** [comment]
@saintsoldierx so should I completely disable (remove) from all the search pages ?

**Comment by saintsoldierx** [comment]
@gurjit03 for now, can you add an option in the settings to turn it off/on? Default should be off for now.

**Comment by saintsoldierx** [comment]
@gurjit03 i am fine with it being per browser tab... but if we have SSO working, can we not make this as part of a profile preference?
