### ISSUE TITLE
Highlight the words in the results based on query

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#476]
![image](https://user-images.githubusercontent.com/6177621/40573689-971419ae-60e2-11e8-8fc3-266178685354.png)

**Comment by bogas04** [comment]
This is kinda tricky thing to do.

We can only color if we use spans. And when we use spans, larivaar gets bit complicated.  And then we're changing larivaar implementation heavily. I'm bit confused.

And then there's unicode, and other cases like romanized/words.

@ManjotS the color choice has to be changed too coz larivaarAssist uses that color.

<img width="443" alt="screen shot 2018-06-16 at 2 40 46 pm" src="https://user-images.githubusercontent.com/6177621/41497458-49802d80-7173-11e8-991a-bbbfed832ff8.png">

**Comment by bogas04** [comment]
Okay i've supported unicode as well as all other search types (except translation/ang).

Larivaar would be bit complicated and maybe we can release for it later.

@tarunsingh5 @ManjotS @saintsoldierx please give your feedback. If all looks good i can merge it to dev for testing.


<img width="483" alt="screen shot 2018-06-16 at 3 42 34 pm" src="https://user-images.githubusercontent.com/6177621/41497889-cb4f4b9e-717c-11e8-8753-873233ed810f.png">
<img width="478" alt="screen shot 2018-06-16 at 3 42 49 pm" src="https://user-images.githubusercontent.com/6177621/41497890-cb8b9e8c-717c-11e8-97c4-87f693c0ab9d.png">
<img width="481" alt="screen shot 2018-06-16 at 3 43 03 pm" src="https://user-images.githubusercontent.com/6177621/41497891-cbc484e0-717c-11e8-91e4-59c81dec16e5.png">
<img width="491" alt="screen shot 2018-06-16 at 3 49 21 pm" src="https://user-images.githubusercontent.com/6177621/41497898-e4ff99a4-717c-11e8-8df9-ba385cd08ffb.png">

**Comment by ManjotS** [comment]
What about bisram

**Comment by ManjotS** [comment]
Bisram on should apply everywhere @bogas04
