### ISSUE TITLE
backspace in search input moves cursor to end of string

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#485]
MAKE IT STOPPPPPPP

**Comment by bogas04** [comment]
what?

**Comment by ManjotS** [comment]
type abc
use backspace to remove b
cursor is now after c instead of between a and c

**Comment by bogas04** [comment]
It's some issue with react itself, or the way we're using it. Will study further.

https://github.com/reduxjs/react-redux/issues/525

**Comment by tarunsingh5** [comment]
was this resolved? @bogas04

**Comment by bogas04** [comment]
Nope, not yet

**Comment by psingh86** [comment]
test

**Comment by prebhdevsingh** [comment]
@bogas04 can you please assign this to @inderpreet99
