### ISSUE TITLE
Add meta description and keywords to all pages

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#49]
Add open graph standard headers AND graphics.

Also include relevant titles on pages where possible.

**Comment by bogas04** [comment]
@ManjotS could you share which API has ShabadName?

**Comment by ManjotS** [comment]
needs to be in banidb api, that part was put into a separate github issue. we are good without it for the purposes of this ticket.

**Comment by Gauravjeetsingh** [comment]
@ManjotS Is the shabad name in banidb api now? Anything else needed in this issue?

**Comment by ManjotS** [comment]
@navdeepsinghkhalsa see question above

**Comment by navdeepsinghkhalsa** [comment]
Shabad Name does not exist in the API, no. Where do I get that from the DB?

**Comment by ManjotS** [comment]
ShabadNames table. The name could just be added to current shabad output.

**Comment by saintsoldierx** [comment]
@ManjotS please provide any updates/insights on this please.

**Comment by gurjit03** [comment]
@saintsoldierx @ManjotS what we wanted to write in the description and title for the shabads? We have author name, shabad source in the API source, couldn't see shabad name.

Current the title and description is this
![image](https://user-images.githubusercontent.com/8514802/82902788-a0756d00-9f7d-11ea-8c25-76ab090347a4.png)

**Comment by ManjotS** [comment]
ShabadName is in the API response. It is an ID. That ID will be in the verse section as line id and you would use the content of that line as the title of that shabad.

**Comment by gurjit03** [comment]
@ManjotS thanks veerji, I will have a look.
