### ISSUE TITLE
Web User Site broken

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#508]
Very good work but since site is broken I am using a different app

Please select which platform you are using:-
Web Version

Feedback Type
Site broken

What went wrong?
WTWF.
Site is broken for romamized English .
So before if I searched k b r r. Koi bole ram ram would come , not any more.K b r r should search in romanized english
 
What should have happened instead?
K b r r should search in romanized english
    
How can the issue be recreated by our team?
Just search k b r r

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Vivek Puri

**Comment by tarunsingh5** [comment]
@ManjotS can you verify?

**Comment by ManjotS** [comment]
this is because we switched to soundex. we have a ticket for first letter romanized search i think.

**Comment by ManjotS** [comment]
Closing in favor of #521
