### ISSUE TITLE
Autohide Tools bar and Scroll to top button on mobile

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#513]
We need to hide the scroll to top button and display/font options after like 5 seconds and show them on scrolling up. This gives full screen experience and distracts less from reading baani.

**Comment by ManjotS** [comment]
use sundar gutka as example

**Comment by tarunsingh5** [comment]
there is a scroll to top now right? is this still needed?

**Comment by bogas04** [comment]
This is to hide those as we scroll down to give immersive experience.

**Comment by saintsoldierx** [comment]
Completed.

**Comment by saintsoldierx** [comment]
Just re-opening this as it's only fixed in dev - not pulled to PRD just yet.
