### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [KhalisFoundation/sttm-web#516]
Since telegram messanger provides a strong api support we should create a bot to search gurbani...

**Comment by bogas04** [comment]
@SukhmanpreetSingh Would you like to fork https://github.com/bogas04/sikhjs-telegram-bot and create a STTM version of it?

**Comment by SukhmanpreetSingh** [comment]
i dont now to using coding sorry .... it req high coding skills

**Comment by bogas04** [comment]
@SukhmanpreetSingh no issues jee. If you want I can mentor you for the same :) You'll need to learn a bit of JavaScript.

I've created a [new repo](https://github.com/KhalisFoundation/sttm-telegram-bot) for telegram bot. For now you can try using @SikhJS on telegram and give us your valuable feedback with which we can improve `sttm-telegram-bot`.

**Comment by SukhmanpreetSingh** [comment]
ok ji

**Comment by bogas04** [comment]
Would you like to work on https://github.com/KhalisFoundation/sttm-telegram-bot/issues/1 ? It's a simple find and replace, we need to change all the parts where "SikhJS" is written to "STTM".

**Comment by bogas04** [comment]
Closing this issue as this would be worked out in [sttm-telegram-bot](https://github.com/KhalisFoundation/sttm-telegram-bot)

**Comment by SukhmanpreetSingh** [comment]
bot not working...
