### ISSUE TITLE
Add back button or swipe right gesture to enable back for iPhone

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#520]
## How can authors of this project cause the issue to occur on their systems ?

  1.
  2.
  3.

## What were you trying the project on ?

  - Browser:
  - Browser Version:
  - Operating System:

**Comment by saintsoldierx** [comment]
Safari on iPhone does have back button. @bogas04 can you clarify?

**Comment by bogas04** [comment]
iPhone doesn't have a hardware back button and if users add to home screen they lose the browser UI. Make sense?

**Comment by saintsoldierx** [comment]
Ok, just tried it and makes sense now :)

**Comment by saintsoldierx** [comment]
A back button in top-left of screen would suffice.
