### ISSUE TITLE
Highlighting the words in the results based on query in Larivaar mode

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#523]
We have highlighting the search words on search results page which works great for non-larivaar mode. However, switching/using larivaar mode this feature does not work.

In all modes, let's have opacity of the highlighted words as 100 and those not part of the results as less (maybe 30).

![image](https://user-images.githubusercontent.com/27791330/42432488-9d3f84e6-82ff-11e8-84da-43c51839a414.png)

**Comment by bogas04** [comment]
Sounds great! I'll try a mockup of the same!
