### ISSUE TITLE
Implement mahan kosh lookup

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#53]
hover over word and see bubble (similar to google translate when it does a website)

**Comment by bogas04** [comment]
I love the way [quran.com](http://quran.com) does translations. However we'll have make it on hover for desktops and tap for mobiles.

**Comment by irvanjit** [comment]
srigranth.org has this exact implementation, for reference.

**Comment by bogas04** [comment]
Where is the data source for this?

**Comment by ManjotS** [comment]
This is waiting on @navdeepsinghkhalsa https://github.com/KhalisFoundation/BaniDB-API/issues/27

**Comment by saintsoldierx** [comment]
@ManjotS please can you provide us with status update on this one.

**Comment by saintsoldierx** [comment]
@ManjotS an update please?

**Comment by ManjotS** [comment]
api ticket is tracking status. we need to add endpoint
