### ISSUE TITLE
Quick links

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#533]
Just like Sehaj Paath, we can add quick links to SG.

* For example, time based link to Nitnem Baani.

<img width="672" alt="screen shot 2018-07-20 at 5 20 44 pm" src="https://user-images.githubusercontent.com/6177621/43001020-55fd25fc-8c41-11e8-97d7-1cf9c4a56e98.png">

* We can also check the most visited SG links (maintain client side count maybe) to suggest those directly. This is helpful in case the reader doesn't use STTM for all nitnem baanies. (Like I only do Jaap Sahib from it).

* I also feel that we can move all our top nav bar links to this spot as they're visible on mobile and we don't need to adjust for responsive design.

* Ardas should also be here somewhere.

* This should also greet on Gurpurabs. I think here we can rely on #507 to have a JSON object of all gurupurab dates, manually curated, until we've an intelligent system to deterministically find Gurpurabs.

**Comment by saintsoldierx** [comment]
@bogas04 any ideas how we can get this implemented and move forward?

**Comment by bogas04-swiggy** [comment]
* Time aware baani can be coded right away as we now have baani support.
* A "Did you know" could also be added here that can be powered by backend configuration.
* For gurpurab related data we need to expose an API for same.

If we add #507 then we can easily rely on it for having configuration stored as env variable or something.

**Comment by bogas04** [comment]
* Time aware baani can be coded right away as we now have baani support.
* A "Did you know" could also be added here that can be powered by backend configuration.
* For gurpurab related data we need to expose an API for same.

If we add #507 then we can easily rely on it for having configuration stored as env variable or something.

**Comment by Gauravjeetsingh** [comment]
Japji sahib and rehras sahib quick reminder link is now live in prod.
