### ISSUE TITLE
Print Shabad Option

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-web#535]
**Is your feature request related to a problem? Please describe.**
I want to be able to print out shabads easily

**Describe the solution you'd like**
Have a button at the top near the copy/tweet button

**Describe alternatives you've considered**
copy-pasting but a simple one button to create a printable version would be even better - perhaps have it sytlized

**Comment by tarunsingh5** [comment]
@bogas04 this is being used by kids at Gurmat Camp - if we can prioritize this that would be great

**Comment by pdvsingh** [comment]
Sikhnet has integration with STTM - you can put any shabad ID after this URL and it will pull data from our DB

https://www.sikhnet.com/shabad-printer/Shabad-ID

example: https://www.sikhnet.com/shabad-printer/21

**Comment by ManjotS** [comment]
All we need a css for print .

**Comment by Gauravjeetsingh** [comment]
Closing it, as it's deployed to prod.
