### ISSUE TITLE
sundar gutka scroll position on back button

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#542]
**Describe the bug**
scroll positions are strange

**To Reproduce**
1. Go to Sundar Gutka index
2. Click on a bani
3. Scroll down to the end of the bani
4. click back
5. you are the at end of the bani list and not at the scroll position in the index that you were on when clicking the bani.

**Expected behavior**
clicking back from a bani should bring us to the same scroll position in the index that we left from.

**Desktop (please complete the following information):**
 - OS: MacOS HS
 - Browser Firefox

**Comment by saintsoldierx** [comment]
See #705
