### ISSUE TITLE
[WEB] An asterisk when searching should check for shabads using all characters 

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-web#543]
Similar to https://github.com/KhalisFoundation/sttm-desktop/issues/268

**Comment by ManjotS** [comment]
https://github.com/KhalisFoundation/sttm-desktop/pull/303

**Comment by tarunsingh5** [comment]
@Gauravjeetsingh

**Comment by tarunsingh5** [comment]
pinging this up

**Comment by Gauravjeetsingh** [comment]
The search highlight was done with operators from sttm-web. 
Needs one final testing, when the operators are complete from API side.

**Comment by Gauravjeetsingh** [comment]
Working on prod now, closing this.
