### ISSUE TITLE
Allow easy way to print shabad

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#549]
How do I print the shabad displayed?

Please select which platform you are using:-
Desktop Version

Feedback Type
Questions

What went wrong?

 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
Sarbjit Singh

**Comment by pdvsingh** [comment]
#535 seems like a duplicate

**Comment by bogas04** [comment]
It is.
