### ISSUE TITLE
Web User not sure is this bur or not

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#558]
when in larivaar mode i search whole word it shows all shabads , but it doesn't highlight the word i searched, when i switch to pad ched it show me in green color , but not in larivaar mode.

Please select which platform you are using:-
Web Version

Feedback Type
not sure is this bur or not

What went wrong?
when in larivaar mode i search whole word it shows all shabads , but it doesn't highlight the word i searched, when i switch to pad ched it show me in green color , but not in larivaar mode.

it should highlight the searched word in larivaar mode too.
 
What should have happened instead?
it should highlight the searched word in larivaar mode too.
    
How can the issue be recreated by our team?
search following word and turn on larivaar mode it will not highlight the word i searched in search results
 
haumYit doesn't highlight the word i searched in larivaar mode

Which web browser are using?
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

Operating System
Mac OS

Name
Satpreet Singh

**Comment by tarunsingh5** [comment]
duplicate - fixed in #590
