### ISSUE TITLE
Add ability to control desktop

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#559]
Pre-req: https://github.com/KhalisFoundation/sttm-desktop/issues/140

Add admin to remote sync feature.

User enters remote admin code. sttm web recognizes that its admin  and not normal sync, allows user to click a line and control remote server.

**Comment by Gauravjeetsingh** [comment]
Bani Controller is now in prod. Anything pending regarding this issue @saintsoldierx veerji?
