### ISSUE TITLE
Add GDPR cookie notice + settings

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#574]
add cookie settings in one of the settings menu and make available as popup for anyone who has not set.

**Comment by bogas04** [comment]
We use only one cookie for dark theme optimization. That's all :p

Please let me know how this is supposed to be added (UI wise)

**Comment by ManjotS** [comment]
how are we remembering prefs?

Lets rename display drop down to settings and add a button in there for cookie settings and then a modal.

modal would be something like this with list of cookies (and global switch) 

![image](https://user-images.githubusercontent.com/644885/48957525-dad7f700-ef0d-11e8-82ec-133cc3ecb69e.png)


we can store a cookie with the cookie pref regardless so if they turn off cookies, lets remember that. There should be a banner linking to the modal for anyone who hasnt yet seen the banner or opted in/out

**Comment by bogas04** [comment]
We use cookie for dark mode (shared with our server), localStorage for other stuff (not shared with our servers). However, we do get google analytics events for actions, but we can't fingerprint the user in that case, so anonymous data.

What's the take? Do we need to show cookie message if no sensitive data is stored anywhere?

SikhiToTheMax website uses two web technologies to store your preferences.

* [Cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)
If you choose "Dark Mode", we save that preference in a cookie so as to serve dark mode website to you from the server itself. This preference is naturally shared with our servers.

* [LocalStorage](https://developer.mozilla.org/en-US/docs/Web/API/Storage/LocalStorage)
LocalStorage (not shared with our servers at all) is also used to save your display and font preferences, and other things like previous read page.
