### ISSUE TITLE
Ability to choose fonts

### ISSUE THREAD

**Issue by irvanjitsingh** [KhalisFoundation/sttm-web#58]
Ability to change the default ASCII/unicode fonts

**Comment by bogas04** [comment]
Is this resolved ?

**Comment by ManjotS** [comment]
no.. this would fall under display options

**Comment by bogas04** [comment]
What exactly are we looking at here?

**Comment by ManjotS** [comment]
similar to font chooser in sundar gutka options.

We can use those fonts in fact (web akhar +thick +heavy, anmol lipi, etc)

**Comment by ManjotS** [comment]
most likely just a drop down in font options

**Comment by tarunsingh5** [comment]
fixed
