### ISSUE TITLE
Service worker support

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#588]
Final step stopping sttm from becoming a full PWA.

Why?

* Website loads even when there's no network. We can tweak it to load whatever SG/Angs the user has ever loaded.
* Repeat visits are much much faster.

Why not?

* Doing it incorrectly can lock users on an old version of website with only way to clear being to delete all site storage settings.

**Comment by bogas04** [comment]
We shouldn't reopen this as the support is there, we just chose to turn it off as of now. In fact we can enable it now. Just remove the env variable kill_service_worker

**Comment by saintsoldierx** [comment]
@bogas04 do you want to enable it now? Should I close this?

**Comment by Gauravjeetsingh** [comment]
A self-destroying service worker is now activated in production. Closing this issue. We can reopen it if we get any new cache issue from users.
