### ISSUE TITLE
Add Array.from polyfill

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#591]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
It does not find anything for any search
 
What should have happened instead?

    
How can the issue be recreated by our team?
Tried for hxvMqr as full word in Gurmukhi.
Tried Bdns as First letter from start.

Which web browser are using?
Internet Explorer 11

Operating System
Microsoft Windows

Name
Manjit Singh

**Comment by bogas04** [comment]
Tests on IE11 using browser stack
