### ISSUE TITLE
Meta tags for shabads should contain shabad name and translations

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#594]
ShabadName is available now for each shabad, sort of like an article title. Use this for better SEO

**Comment by bogas04** [comment]
Can you share the API/contract?

**Comment by bogas04** [comment]
Closing as this is duplicate of #49

**Comment by ManjotS** [comment]
@Divjot Singh <bogas04@gmail.com> this isnt a duplicate, this is a separate
issue we wanted done later. Set by aman singh
