### ISSUE TITLE
Options panel design separation

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#595]
Would like to make option panels a bit more clearer by adding a grey background as follows:-

https://www.sikhitothemax.org/assets/css/bundle.css

```
@media screen and (min-width: 46em)
.display-options, .font-options {
    background: #e1e1e1;
}

.shabad-controller-toggle, .display-option-toggle, .font-option-toggle{
background:white;
}
```

**Comment by Gauravjeetsingh** [comment]
@saintsoldierx 

How about adding a little box shadow to the options panel to make it clearer?
![Screenshot from 2019-04-30 13-55-39](https://user-images.githubusercontent.com/1990932/57008708-94e73380-6c0f-11e9-9c71-d68228949ea9.png)

**Comment by saintsoldierx** [comment]
Closing this as #674 is sufficient.
