### ISSUE TITLE
Better SG for Desktop

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#599]
Please select which platform you are using:-
Desktop Version

Feedback Type
Enhancements

What went wrong?
Waheguru ji ka Khalsa Waheguru ji ki Fateh,

with Wahegurus Kirpa I am responisble for the Laptop in the Gurdwara.
I like the new version, its much better than the old version, but there is one function missing.

The Sundar-Gutka function with Nitnem, Aarti, Anand Sahib, Salok Mehla 9. etc. 
So f.e. now if the time for Samathi is coming, I have to open Anand Sahib separately with Salok, or I have to type in the Ang for Salok Mehla 9. 
It will be much easier with this additional function. 

So pls add the Sundar-Gutka function. 

Thank you for releasing and updating the software.

Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh. 
 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
Gurmeet Singh Soni

**Comment by bogas04** [comment]
Desktop issue
