### ISSUE TITLE
Add titles to Shabads on server side for better SEO

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#624]
Combination of first, rahao and last line can be used as a title.

**Comment by tarunsingh5** [comment]
Manjot has done some work on this for related shabads

**Comment by tarunsingh5** [comment]
@ManjotS can you sync w/ @bogas04  on this

**Comment by ManjotS** [comment]
api needs to expose titles this is waiting on @navdeepsinghkhalsa

**Comment by saintsoldierx** [comment]
So does latest api support this now? @ManjotS

**Comment by ManjotS** [comment]
There wasn't an api ticket for this. I can just add name to the shabad lookup?

**Comment by ManjotS** [comment]
https://github.com/KhalisFoundation/banidb-api/pull/128
