### ISSUE TITLE
We should display link to STTM mobile app as well

### ISSUE THREAD

**Issue by pdvsingh** [KhalisFoundation/sttm-web#626]
Just like we display link to download desktop app, we should add link somewhere to the homepage to the mobile app (iOS / Android) by SHARE.

**Comment by gurpreet-hanjra** [comment]
Should the links to iOS and Android app be in footer, beside Desktop app link? I can work on this, please let know

**Comment by saintsoldierx** [comment]
@gurpreet-hanjra yes please.

**Comment by saintsoldierx** [comment]
Maybe links would have icons like:
Mobile: [iOS logo] [android logo]

@gurpreet-hanjra

**Comment by saintsoldierx** [comment]
@gurpreet-hanjra sorry, hope u dont mind i took this one, i wanted to try my hand at doing something :)
