### ISSUE TITLE
Web User mistake

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#630]
-

Please select which platform you are using:-
Web Version

Feedback Type
mistake

What went wrong?
https://www.sikhitothemax.org/shabad?id=3661

The last line is having prosperity spelling wrong. Thankscorrection please
 
What should have happened instead?

    
How can the issue be recreated by our team?
https://www.sikhitothemax.org/shabad?id=3661 
Check the link

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Prabh Singh

**Comment by tarunsingh5** [comment]
was not able to find the word where the user stated - closing issue
