### ISSUE TITLE
in larivaar view - Adhak character is broken

### ISSUE THREAD

**Issue by harpreetkhalsagtbit** [KhalisFoundation/sttm-web#635]
**Describe the bug**

**To Reproduce**
1. Go to 'search'
2. Click on 'search field'
3. enter 'Angh' and press enter

**Expected behavior**
ਪਰੱਮਪੁਰਖਪਾਇਹੋਂ॥੩੫॥

**Screenshots**
![Screenshot 2019-03-09 at 2 57 08 PM](https://user-images.githubusercontent.com/2958292/54069232-ffb56780-427b-11e9-8c9c-634651388796.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tarunsingh5** [comment]
@bogas04 should we deploy to prod?

**Comment by tarunsingh5** [comment]
@Gauravjeetsingh can you take a look here - it doesnt appear to be fixed in prod

**Comment by harpreetkhalsagtbit** [comment]
yes, not working on production

still working on - `adhakInLarivarIsBreaking` branch
pulled latest master branch and working there too.

let me know, its a bug in code and production is running which branch?

**Comment by Gauravjeetsingh** [comment]
@tarunsingh5 It worked for me though. I tested it in a private window. We did a rollback once after pushing it. Maybe @bogas04 singh ji redeployed it now.

![Screenshot from 2019-05-26 10-08-08](https://user-images.githubusercontent.com/1990932/58384944-3f980b00-7f9e-11e9-9111-7b3c52b39d8d.png)

**Comment by Gauravjeetsingh** [comment]
@tarunsingh5 Yeah, the fix is not deployed to production. We had to do a rollback because of that cache issue. This is fixed in version 1.1.12, Current version on production is 1.1.11-30042019

**Comment by bogas04** [comment]
Please refer to dev to see if this is actually fixed. Prod deployment shall
be done soon.

**Comment by tarunsingh5** [comment]
deployed to prod
