### ISSUE TITLE
HTTPS certificate issue after submitting feedback

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#638]
Getting following after submitting feedback:

![image](https://user-images.githubusercontent.com/6245927/54355508-48579100-467f-11e9-94a9-a15e36267e3b.png)

It's trying to load `https://sikhitothemax.org/` 

Otherwise as well, https://www.sikhitothemax.org/ works fine but https://sikhitothemax.org/ does not

**Comment by bogas04** [comment]
@mkhalsa

**Comment by plug-n-play** [comment]
@ManjotS Kind reminder

**Comment by ManjotS** [comment]
im not sure how to resolve this at this time.. let me think on it

**Comment by pdvsingh** [comment]
Can we just do javascript redirect from https://sikhitothemax.org to https://www.sikhitothemax.org?

window.location.href = "https://www.sikhitothemax.org"

**Comment by Gauravjeetsingh** [comment]
Doing it via javascript would be a hack way, and has a possibility of causing unexpected behavior in some cases.
We can change the redirect URL in the jotform configuration
Or just add the same A record for https://sikhitothemax.org in DNS management

**Comment by plug-n-play** [comment]
@ManjotS  - Please see @Gauravjeetsingh  comment above ^^

Also, as a quick fix can we not edit the redirect url on `https://form.jotform.com/80266126732151` from `https://sikhitothemax.org/` to `https://www.sikhitothemax.org/`
