### ISSUE TITLE
Sehaj paath mode for web and mobile

### ISSUE THREAD

**Issue by irvanjitsingh** [KhalisFoundation/sttm-web#64]

**Comment by bogas04** [comment]
Need help with UI. [This](https://bogas04.github.io/SikhJS/#/sggs/1) is how [SikhJS](https://bogas04.github.io/SikhJS/#/) does it.

**Comment by ManjotS** [comment]
My preference is to either direct link sehaj patt mode to larivaar.com OR include the larivaar app at sikhitothemax.org/sehajpatt or sikhitothemax.org/larivaar

This also requires @navdeepsinghkhalsa to utilize shabados api for larivaar.com

**Comment by ManjotS** [comment]
In our status meeting, we agreed to make it more like twitter/never ending reddit wherein when its enabled, split mode is disabled, and it auto loads the next ang as you scroll down (even if you are in a shabad view).

To do this, it should hook into the api next/prev just as the arrows do.

**Comment by bogas04** [comment]
@ManjotS I think that interaction might be bit tricky. Like I might be reading last line and suddenly the page refreshes. What do you suggest?

**Comment by bogas04** [comment]
@tarunsingh5 @navdeepsinghkhalsa please comment on above.

**Comment by irvanjit** [comment]
@ManjotS there should still be separators indicating where the ang starts and ends

**Comment by ManjotS** [comment]
@bogas04 can we add it when half way scrolled and keep position? 

@irvanjit I agree, maybe we can use a flourish separator from the font set (see Asa Di Var in sundar gutka)

**Comment by irvanjit** [comment]
A simple addition to improve the ang view would be a textbox to jump to any ang in the header like SikhJS has @bogas04 @ManjotS

**Comment by ManjotS** [comment]
imo thats what larivaar learner is for. you can type ang number easily already in the search box which is in header.

**Comment by saintsoldierx** [comment]
For initial implementation, we can ignore points 3 & 5 for now.
