### ISSUE TITLE
Enhance Gurmukhi Keyboard

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#644]
Please select which platform you are using:-
Web Version

Feedback Type
Enhancements

What went wrong?
Expanding the Gurumukhi keyboard to include page2 below page for better user interaction :

When using the Gurumukhi keyboard to search for a partcular Keertan, it shows pages 1 and the 2 ( for the sihari, bihar etc).

Would it be possible for your developers to expand the keyboard to include page2 below so that the user doesnt have to keep going to page2 to search for matras

Thans
 
What should have happened instead?

    
How can the issue be recreated by our team?
Currently the user has click 2 to go to page 2 of the keyboard to choose the matras.

Additional clicks to complete the word

Which web browser are using?
 

Operating System

Name
Prabhjeet Singh

**Comment by bogas04** [comment]
@saintsoldierx what do you suggest?

**Comment by Gauravjeetsingh** [comment]
I liked the design of punjabi keyboard in gboard (google keyboard for android). If we can imitate that, it would be awesome.

**Comment by saintsoldierx** [comment]
@Gauravjeetsingh Could you add a screenshot of what it looks like in Android?

**Comment by Gauravjeetsingh** [comment]
I like how the keyboard changes the button labels, to show matra on last typed character.

![keyboard](https://user-images.githubusercontent.com/1990932/59152177-12af1380-89f4-11e9-9335-61dee673c144.gif)

**Comment by saintsoldierx** [comment]
I like that idea - let's move forward with this.

**Comment by Gauravjeetsingh** [comment]
@saintsoldierx This will take a little longer, and I haven't started on it yet. Let's move this to August milestone.

**Comment by Gauravjeetsingh** [comment]
New keyboard is now live, closing it out.
