### ISSUE TITLE
User has requested PDF of SGGS shabads

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#646]
Virji, I wanted to ask if you had the Guru Granth Sahib Ji separated by Shabads but in the original order that can be emailed to me.  If this is possible please email this to me.

Please select which platform you are using:-
Desktop Version

Feedback Type
Comments

What went wrong?

 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
Harvinder Singh

**Comment by bogas04** [comment]
@tarunsingh5 do we want to provide a resources page where this could be shared?

**Comment by tarunsingh5** [comment]
i dont even know what this is exactly, i think we can add a few links in the help or about maybe?

**Comment by bogas04** [comment]
Yup, can be done!

**Comment by tarunsingh5** [comment]
@bogas04 can you prioritize this accordingly

**Comment by bogas04** [comment]
Do you have the links which we should add?

**Comment by tarunsingh5** [comment]
@bogas04 take a look at vidhia.com maybe?

**Comment by pdvsingh** [comment]
Most likely looking for the hukamnama PDF file. This is not related to STTM web so we should close.

**Comment by tarunsingh5** [comment]
closing this
