### ISSUE TITLE
Users should be able to report mistakes or errors from within the app

### ISSUE THREAD

**Issue by irvanjitsingh** [KhalisFoundation/sttm-web#66]
Perhaps a button beside the share links, or report mistake>select pangti

**Comment by tarunsingh5** [comment]
@ManjotS any update on this?

**Comment by tarunsingh5** [comment]
cant they already do this via the feedback form?

**Comment by bogas04** [comment]
They can, and in fact in case of error we ask them to do so.

![screenshot_20180327-092824](https://user-images.githubusercontent.com/6177621/37946094-401500fc-31a1-11e8-901c-2d2f29573581.jpg)

**Comment by bogas04** [comment]
I guess we can add another link in the Shabad "Report a Mistake", that basically redirects to Feedback link.

**Comment by ManjotS** [comment]
no this ticket was made previously for people to suggest changes line by line (similar to google translate)

the suggestion would go into banidb backend in a separate queue, if approved, it would move to the normal queue for 2 votes etc, if one delete, its removed.

the banidb cp I can take care of, but the submission, editor part is front end

**Comment by tarunsingh5** [comment]
i dont think we need this - the feedback form is sufficient imo - this is a nice to have but not a have to have - calling this a p3

**Comment by irvanjit** [comment]
IMO mistakes with gurbani and features to help resolve these should be given priority. It's likely there's still many that exist that are undiscovered. Better enabling crowdsourced correction should be worth looking into.

**Comment by ManjotS** [comment]
The report tool should just submit an email via banidb.com wordpress contact but should include current sttm page and line id and allow the user to suggest alternate spelling or whatever and comments

**Comment by saintsoldierx** [comment]
A button or similar on the page to easily report mistakes etc would be great.

**Comment by saintsoldierx** [comment]
Something simple like this to begin with.

![image](https://user-images.githubusercontent.com/27791330/83982002-ae10e800-a8d7-11ea-931c-477992828eba.png)
![image](https://user-images.githubusercontent.com/27791330/83982006-b6692300-a8d7-11ea-8739-ef6b5ba3028c.png)

**Comment by saintsoldierx** [comment]
As to not clutter the interface anymore than it is already, i am going to close this. We get many submissions by the new Freshdesk support link which I believe is adequate.
