### ISSUE TITLE
Web User Sundar gutka

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#660]
Maybe reboot the servers

Please select which platform you are using:-
Web Version

Feedback Type
Sundar gutka

What went wrong?
Sundar gutka page not workingShould work
 
What should have happened instead?

    
How can the issue be recreated by our team?
hit this link
https://www.sikhitothemax.org/sundar-gutka

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Bhupinder singh sachdev

**Comment by tarunsingh5** [comment]
this was related to the bad push and is now resolved
