### ISSUE TITLE
Support IDs query string

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#67]
https://www.sikhitothemax.org/results.asp?Title=Tenth+Gate&IDs=2188,3700,4427,6279,6357,14952,15422,15426,16162,18788,20012,21465,21468,22017,31114,38754,39324,40271,41556,42657,44002,44005,44148,44300,44339,45663,47891,47897,56392,56702,59785

This should redirect and search for multiple IDs so that people can make a custom doc

**Comment by navdeepsinghkhalsa** [comment]
@ManjotS From where does the Title parameter come? Was there a listing of topics on the previous site that we need to replicate?

**Comment by ManjotS** [comment]
unsure. We need to ask sttm folks

**Comment by ManjotS** [comment]
So after giving this thought, title can be set by whatever is calling this URL.

This can also be used by keertan network.. for example a track that has 5 shabads could just have the track name as title and list the ids.

**Comment by bogas04** [comment]
Does BaniDB support this? If yes then I can implement it.

**Comment by navdeepsinghkhalsa** [comment]
BaniDB doesn't yet support this. If there is a desire to get this out quickly, it would have to be done as multiple calls for the time-being

**Comment by ManjotS** [comment]
requires banidb support first

**Comment by ManjotS** [comment]
https://github.com/KhalisFoundation/BaniDB-API/issues/28

**Comment by bogas04** [comment]
I think we can do this from client side until backend is ready.

**Comment by saintsoldierx** [comment]
@ManjotS do you think we still need to do this? What is use case for it?

**Comment by ManjotS** [comment]
the use  case is for custom pothis or groups of shabads (one example is you
asking me for full anand sahib).

Its also an STTM2 feature that needs to be ported forward.

**Comment by saintsoldierx** [comment]
So to make sure I got this correct - 

1. User can choose multiple shabad IDs
2. The application then has a way of displaying each shabad individually but in sequence. 
3. User should have a way of navigating through the shabads using next, previous and maybe a dropdown index.

Is that correct @ManjotS ?

**Comment by ManjotS** [comment]
it should just display in one page like a bani

**Comment by ManjotS** [comment]
api provides this ability with https://github.com/KhalisFoundation/banidb-api/pull/110

**Comment by tarunsingh5** [comment]
@ManjotS whats the use case here?

**Comment by ManjotS** [comment]
Kind of discussed in the thread.. its an STTM feature that was around for years but we broke and haven't fixed.

It allows people to create their own compilations. Saw it on a lot of blogs years ago for example if someone wanted to create a set of shabads for some topic.

**Comment by ManjotS** [comment]
It also enables kirtan sites to link to lyrics easily
