### ISSUE TITLE
Center-align View

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#670]
It would be good to have `Center-Align` option. E.g.

![image](https://user-images.githubusercontent.com/6245927/57551353-70652700-7386-11e9-96ce-a65676aaff77.png)

**Comment by pdvsingh** [comment]
Closing as center align is available on dev.

**Comment by bogas04** [comment]
Umm? It's fixed in dev right?

**Comment by Gauravjeetsingh** [comment]
Few issues I found with this:
- Clicking on Reset display has no effect on center align. 
- Also, shouldn't we display the center align option before the reset display button?

**Comment by bogas04** [comment]
Good catch @Gauravjeetsingh.

@plug-n-play could you please create a follow up PR for these points. Thank you so much!

**Comment by plug-n-play** [comment]
Done - https://github.com/KhalisFoundation/sttm-web/pull/698
