### ISSUE TITLE
Ability to login, Create bookmark list, and save/bookmark Shabads in personal list

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-web#671]
It would be great if we can login to STTM, create a list of bookmarks. E.g.
- Benti Shabad
   - Rakho Apni Saran Prabh
- Ustat Shabad
  - Madho Hum Aise tu Aisa

etc.
This would be everyone's own personalised list. Although, this would help many, this may prove specially helpful to Keertaniyas

**Comment by bogas04** [comment]
Duplicate of #415
