### ISSUE TITLE
Adapt to be a PWA

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/sttm-web#68]
[https://developers.google.com/web/progressive-web-apps/checklist](https://developers.google.com/web/progressive-web-apps/checklist)

**Baseline Progressive Web App Checklist**
- [x] Site is served over HTTPS
- [x] Pages are responsive on tablets & mobile devices
- [x] The start URL (at least) loads while offline (Service worker)
- [x] Metadata provided for Add to Home screen
- [x] First load fast even on 3G (Code splitting, SVGs)
- [x] Site works cross-browser
- [x] Page transitions don't feel like they block on the network (React-router)
- [x] Each page has a URL (We're an SPA with proper routes)

**Comment by bogas04** [comment]
Not everything is required to qualify as a PWA. The bare minimum is that we use a `webmanifest` file to describe `Add to Homescreen` layouts and load fast enough on 2G/3G. Following that we can use a service worker that caches all khajana responses so that user can see what he/she has already searched.

Todo List:

* [ ] Create webmanifest file. [ManifoldJS](http://manifoldjs.com/generator) can help us to be cross-platform.
* [ ] Create service worker for all assets and khajana API responses.
* [ ] ...

**Comment by navdeepsinghkhalsa** [comment]
You're right. I meant to make it two lists, but neglected to put in the header to separate the two lists. I'll put it in now

**Comment by bogas04** [comment]
Recent merge of `pwa` added basic functionality

![screenshot_20170221-094517](https://cloud.githubusercontent.com/assets/6177621/23150603/a4b51482-f81a-11e6-95a1-cf9f14646021.png)
![screenshot_20170221-094545](https://cloud.githubusercontent.com/assets/6177621/23150605/a4b966b8-f81a-11e6-93cb-d8b7f3475dda.png)
![screenshot_20170221-094531](https://cloud.githubusercontent.com/assets/6177621/23150606/a4bd571e-f81a-11e6-897d-f4d38daf2b67.png)
![screenshot_20170221-094514](https://cloud.githubusercontent.com/assets/6177621/23150604/a4b96442-f81a-11e6-8609-85a95513d37e.png)

**Comment by bogas04** [comment]
We can take up the remaining parts slowly. Integrating Service worker should be the next step to cache responses of *.php, *.js and *.css.

**Comment by bogas04** [comment]
Although we've Service Worker running well, I am not confident about it, I want to test it properly (updates and all) before pushing.

**Comment by saintsoldierx** [comment]
I believe this is (mostly) done - @bogas04 @navdeepsinghkhalsa please confirm before closing. Add new tasks as needed.

**Comment by bogas04** [comment]
@saintsoldierx we're pretty much a PWA, just that we lack service-worker support. I am bit worried to add it just now as it has potential to cause cache hazard.

**Comment by bogas04** [comment]
I'm closing the issue in favour of #588 as it is more concise.
