### ISSUE TITLE
Aunkar Char error (dev) 

### ISSUE THREAD

**Issue by AkalUstat** [KhalisFoundation/sttm-web#687]
**Describe the bug**
the aunkar char appears slightly offset from its parent char when in the following fonts: Unicode, anmol lipi (all versions), and gurbaani akhar (all versions). 
Seems fine in the noto family of fonts
<img width="672" alt="Screen Shot 2019-05-26 at 4 39 11 PM" src="https://user-images.githubusercontent.com/43657841/58388533-0e86fd00-7fd5-11e9-9e70-92fb7e801c85.png">

**To Reproduce**
1. Search for Badshaw Darvesh Gur Gobind Singh
2. Line 
raahamaula-rahaam guroo gobi(n)dh si(n)gh showcases the error

**Desktop (please complete the following information):**
MacOS, Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
on dev.sikhitothemax.com

**Comment by Gauravjeetsingh** [comment]
Change submitted in the bani db API
