### ISSUE TITLE
Random Shabad not working in some cases

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#690]
It's not a working on my android phone.  No idea what type of Web browser I have. 

Please select which platform you are using:-
Web Version

Feedback Type
See below

What went wrong?
Nothing comes up when you hit the random shabd buttonGet a random shabd 
 
What should have happened instead?

    
How can the issue be recreated by our team?
Select random shabd 

Which web browser are using?
Chrome 

Operating System
Other

Name
Rupi Kaur

**Comment by bogas04** [comment]
Works for me. Can we contact them for more info?

**Comment by tarunsingh5** [comment]
this is the cache issue - closing
