### ISSUE TITLE
Add new fonts for Gurbani

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#696]
Add prabhki and raaj to list of fonts.

https://www.sikhnet.com/Gurmukhi-Fonts

**Comment by ekas** [comment]
@Gauravjeetsingh & @saintsoldierx can I take up this issue. As, I have already made the changes and even tested it. Further, just wanted to get it reviewed with you guys to check whether I am on right track or not.

**Comment by Gauravjeetsingh** [comment]
@ekas ji, are you still working on this? Let me know if you are stuck somewhere.

**Comment by ekas** [comment]
Yeah, but got stuck with the change in font file as you mentioned last. I will raising the PR again. If you could help me with that.

**Comment by Gauravjeetsingh** [comment]
@ekas 
Have you tried using this https://fontforge.github.io/en-US/ to fix the character problem in raaja font.

If not, go ahead, and let us know if it works.

**Comment by saintsoldierx** [comment]
There is an issue with Raaj fonts but have added Prabhki. Will revisit again in future to add more.

**Comment by saintsoldierx** [comment]
Re-opening as it's only fixed in dev, not merged with prd yet.
