### ISSUE TITLE
[Object Object] error

### ISSUE THREAD

**Issue by AkalUstat** [KhalisFoundation/sttm-web#700]
**Describe the bug**
When searching for nonexsistant shabad or incorrctly searching shows following image:
![AF6B1C89-64D2-40F6-8B02-F5CD893A564C](https://user-images.githubusercontent.com/43657841/58737260-b45fb080-83b5-11e9-8737-faa02cdcda9c.jpeg)

**To Reproduce**
1. Incorrectly search for or search for a nonexsistant shabad

**Expected behavior**
An error message such as something went wrong shows up

**Desktop (please complete the following information):**
 All OSs and all devices

**Comment by Gauravjeetsingh** [comment]
This is now fixed in production.
