### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#703]
Error page from sttm

Please select which platform you are using:-
Web Version

Feedback Type
Not working

What went wrong?
Opens to ....something went wrong pageAccess to select and read
 
What should have happened instead?
Should have been able to select what  I wanted to read
    
How can the issue be recreated by our team?
Open the program  Error page  

Which web browser are using?
Chrome ?

Operating System
Microsoft Windows

Name
Nana Delanoy

**Comment by bogas04** [comment]
Need more information. Maybe we've already fixed this by killing service worker. @tarunsingh5 do you think we should keep this open?

**Comment by tarunsingh5** [comment]
closing this out since this is likely the service worker issue
