### ISSUE TITLE
Window jumps a little while scrolling a Shabad

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#706]
**Describe the bug**
In mobile view, when you scroll from top to bottom in a Shabad page, the window jumps around the display options region.

**To Reproduce**
1. Go to any Shabad page in mobile view
2. Scroll down until mid of shabad
3. Observe the scroll jump

**Expected behavior**
Shouldn't happen

**Screenshots**
https://gfycat.com/coldopenbeagle

**Desktop (please complete the following information):**
 - OS: Android 
 - Browser Chrome
 - Version 72

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bogas04** [comment]
@Gauravjeetsingh

**Comment by Gauravjeetsingh** [comment]
I think I know why this is happening. Will fix it.
