### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#707]
ਵਾਹਿਗੁਰੂ! Something isn't working correctly
This is really unusual. You may want to hit the Feedback button at the bottom of this page, and report this issue to our Sevadaars to fix it before others face it.

Please select which platform you are using:-
Web Version

Feedback Type
Comments

What went wrong?

 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
sawaran singh

**Comment by bogas04** [comment]
Need more information

**Comment by bogas04** [comment]
Need more information. Maybe we've already fixed this by killing service worker. @tarunsingh5 do you think we should keep this open?

**Comment by tarunsingh5** [comment]
lets close this out - this is from the service worker issue
