### ISSUE TITLE
Random hukumnama button doesn't work

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#709]
Please select which platform you are using:-
Desktop Version

Feedback Type
Bug Reports

What went wrong?
random hukumnama button doesn't work. thanks
 
What should have happened instead?

    
How can the issue be recreated by our team?
please make it work if you can. thanks

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Jagvir Singh

**Comment by bogas04** [comment]
Do we even have such button?

**Comment by tarunsingh5** [comment]
both the random shabad and hukamnama buttons now work, so closing this out
