### ISSUE TITLE
Element alignment is off on iPad Pro 11

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-web#719]
**Describe the bug**
Header alignment is off on shabad pages 

**To Reproduce**
1. Go to STTM
2. Click on hukamnama
3. See error

**Expected behavior**
Aligned elements

**Screenshots**
Attached

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11 2018
 - OS: iPad OS 13
 - Browser: chrome
![48F11D26-08A1-4E17-97D6-3494714E68C8](https://user-images.githubusercontent.com/35271830/60453732-c7e57d80-9be6-11e9-8970-445bd084a0da.jpeg)

**Comment by bogas04** [comment]
@Gauravjeetsingh /@plug-n-play  would you like to fix the breakpoints of media queries to fix this?

**Comment by ekas** [comment]
Working fine now. Nicely done. I guess issue should get resolved now.

![Screenshot 2019-07-19 at 11 57 52 PM](https://user-images.githubusercontent.com/4580483/61557150-1f0d9e00-aa81-11e9-87e1-4a7482f46064.png)

**Comment by tarunsingh5** [comment]
@Gauravjeetsingh make sure we close this ticket when its pushed to prod

**Comment by bogas04** [comment]
Fixed in prod.
