### ISSUE TITLE
Can't highlight a word anymore

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#720]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
When attempting to highlight a single word, the whole pankti is highlighted. 
 
What should have happened instead?
Only the word that you highlight should be highlighted. 
    
How can the issue be recreated by our team?
Try to highlight a single word 

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Kulpreet Singh

**Comment by bogas04** [comment]
This is a feature now. @saintsoldierx @Gauravjeetsingh  do we need to reevaluate whether to keep this feature or not?

**Comment by ManjotS** [comment]
yeah ive been getting complaints about this on insta. There needs to be a way to meet both use cases.

**Comment by saintsoldierx** [comment]
Merge request #806 - pending conflict resolution.
