### ISSUE TITLE
Issue with transliteration searching

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#734]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
My search is not working now on your site please help
I search in gurmukhi in english transliteration 
Like
Jo mange thakur
 
What should have happened instead?
Please help me
Look at the matter sir
    
How can the issue be recreated by our team?
Check out your site
Go for debugging

Which web browser are using?
Chrome 

Operating System
Other

Name
Gurdeep  Singh

**Comment by saintsoldierx** [comment]
Verified issue.

**Comment by bogas04** [comment]
This is fixed now @navdeepsinghkhalsa ?

**Comment by Gauravjeetsingh** [comment]
This is working now. So closing it.
