### ISSUE TITLE
Circle thing appearing in gurmukhi text

### ISSUE THREAD

**Issue by AkalUstat** [KhalisFoundation/sttm-web#740]
**Describe the bug**

**To Reproduce**
1. Set font to: unicode
2. search '
ਬਾਬੀਹਾ ਭਿੰਨੀ ਰੈਣਿ ਬੋਲਿਆ ਸਹਜੇ ਸਚਿ ਸੁਭਾਇ ॥' (for example)
![Screen Shot 2019-07-25 at 7 28 27 PM](https://user-images.githubusercontent.com/43657841/61921560-65944a00-af12-11e9-9976-fd1dd1051ff7.png)

**Expected behavior**
No circle thingy in gurmukhi

**Desktop (please complete the following information):**
MacOS, Firefox V68.0.1

**Comment by saintsoldierx** [comment]
@AkalUstat i am unable to reproduce - has this been fixed?

**Comment by saintsoldierx** [comment]
Unable to reproduce.

**Comment by ManjotS** [comment]
It's Unicode issue

**Comment by saintsoldierx** [comment]
I don't see the issue - can you replicate n send me steps to reproduce?
