### ISSUE TITLE
Pagination not working properly

### ISSUE THREAD

**Issue by pdvsingh** [KhalisFoundation/sttm-web#741]
When you are searching for a Gurbani word, and there are multiple pages, all pages show the same results.

**To Reproduce**
1. Go to https://www.sikhitothemax.org/search?q=nwnk&type=2&source=all&offset=0
2. Click on page 2 or 3
3. You will see the same results on all pages

**Comment by tejbirsingh** [comment]
Also struggled with this one today.

**Comment by navdeepsinghkhalsa** [comment]
This is a result from moving to v2 API, which uses `page` instead of `offset` in the query string.

**Old:**
`https://api.banidb.com/search/nwnk?source=all&searchtype=2&offset=1`

**New:**
`https://api.banidb.com/v2/search/nwnk?source=all&searchtype=2&page=2`

**Comment by bogas04** [comment]
@Gauravjeetsingh We need to update banidb package for this?

**Comment by Gauravjeetsingh** [comment]
@bogas04 yeah! Will open a PR in that repo.
