### ISSUE TITLE
Full Word Translation (English) search should search by whole word

### ISSUE THREAD

**Issue by tejbirsingh** [KhalisFoundation/sttm-web#742]
When I search with Full Word Translation (English), I would expect to see matches of that whole word.

Searching `hem` returns every result that includes `them` or any other word that has the string `hem`. I think it should only return results with the whole word itself.

![image](https://user-images.githubusercontent.com/2815284/61982563-0128c780-afb2-11e9-8314-731eb371f6c1.png)

I believe Full Word implies whole word matching, so I would expect results like this:
![image](https://user-images.githubusercontent.com/2815284/61982598-24ec0d80-afb2-11e9-8dc0-60eed73778f8.png)

**To Reproduce**
Version: web
Select Full Word Translation (English) from the drop down
search a word that can be a part of other words (hem, man, all etc.)

If this was a conscious choice, please ignore this.

**Comment by bogas04** [comment]
@mkhalsa

**Comment by saintsoldierx** [comment]
Is this a BaniDB API issue @ManjotS @tarunsingh5

**Comment by ManjotS** [comment]
No, this is a feature.

For this FR we would need to implement a single word only search on api and
then maybe have a checkbox  on site that switches to it "Full word only"
and also if its in quotes.

Or we could just advise use quotes and implement that within all existing
search types. Please make api ticket.

**Comment by saintsoldierx** [comment]
hem should bring up all results like them. "hem" should only bring up results with hem, not them. Similar to how to Google works. Multiple words _"their feet"_ should bring up results with those words in exact order. _their feet_ should bring up results with those words anywhere in the results.

**Comment by ManjotS** [comment]
Aman, this is an API issue, not a web issue. I would classify quotes under
operators. So this seems to already be fixed in Raj's branch.

**Comment by saintsoldierx** [comment]
Can I close this then @ManjotS ?

**Comment by ManjotS** [comment]
Yes. If it doesn't work as you expect, please open API tickets for specific bugs (check dev first)
