### ISSUE TITLE
Scroll to top doesn't work on Firefox Preview

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#744]
**Describe the bug**
Scroller jumps back down.

**To Reproduce**
1. Go to baani page, preferably long (Jaap Sahib)
2. Scroll to bottom
3. Click Scroll to top
4. See it jump

**Expected behavior**
Should scroll up properly

**Screenshots**
![](https://thumbs.gfycat.com/SophisticatedImperfectCicada-size_restricted.gif)

**Smartphone (please complete the following information):**
 - OS: Android Pie
 - Browser Firefox Preview

**Additional context**
Might be an issue with the browser as it did work on Chrome, but it shouldn't happen nonetheless.

**Comment by saintsoldierx** [comment]
Tested, works.
