### ISSUE TITLE
Undefined ang numbers on search page

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-web#763]
**Describe the bug**
Search page has undefined ang numbers.

**To Reproduce**
1. Search something
2. Observe

**Expected behavior**
Angs should be visible

**Screenshots**
<img width="788" alt="Screenshot 2019-08-05 at 12 52 23 PM" src="https://user-images.githubusercontent.com/6177621/62446296-ff17f300-b77f-11e9-906e-d31c70cb3db0.png">

**Comment by bogas04** [comment]
@Gauravjeetsingh can we refactor the code now to have helper functions like getAng, getAuthor, etc. so that it is consistent across pages. Patching it in every page isn't going to scale well as we discussed earlier. Now that we're on v2 let's do this else it'll only end up causing more bugs in future.

**Comment by Gauravjeetsingh** [comment]
Yeah @bogas04 ji! same thoughts. Would get started on it.

**Comment by Gauravjeetsingh** [comment]
Fixed in prod.
