### ISSUE TITLE
Do not show next arrow when viewing hukamnama from today

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-web#764]
This arrow should be hidden if user is viewing today's hukamnama 
![image](https://user-images.githubusercontent.com/9758101/62509207-217d3100-b7bf-11e9-8f7e-b46a17a70a11.png)

**Comment by Gauravjeetsingh** [comment]
I was waiting on the following issue to get this done.
https://github.com/KhalisFoundation/banidb-api/issues/81

**Comment by Gauravjeetsingh** [comment]
Closing it as it's fixed in prod.
