### ISSUE TITLE
Default "ang" search to SGGSJ

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#767]
**Describe the bug**
The default source for ang should be SGGSJ. Not all sources.

**To Reproduce**
1. Go to 'sikhitothemax.org'
2. Select 'ang'
3. Search for ang 35 for example

**Expected behavior**
Should give a relevant message to say select a source OR default to SGGSJ.

**Comment by saintsoldierx** [comment]
Remove option for "ALL SOURCES" and default to SGGSJ only when ANG is selected. When any other option other than ANG is selected, it should re-show the ALL SOURCES option.

**Comment by Gauravjeetsingh** [comment]
Already created an issue for this #752

**Comment by tarunsingh5** [comment]
@Gauravjeetsingh was this merged to master and deployed?

**Comment by Gauravjeetsingh** [comment]
No, it hasn't been merged to master. There's a PR opened for this release. Need to complete the testing once.

**Comment by tarunsingh5** [comment]
what's our ETA on this - its been pending for almost 2 months

**Comment by Gauravjeetsingh** [comment]
It's ready to be shipped from my side. I and Akal Ustat ji tested it yesterday, and there were no issues found.

Just need someone to merge this PR:
https://github.com/KhalisFoundation/sttm-web/pull/787

**Comment by Gauravjeetsingh** [comment]
Closing it as it's pushed to prod.
