### ISSUE TITLE
Web User Plz solve my problem my neetwork is wotking welll but i am doing sehaj path aur karte vella ruk gaya beech mei roj shaamm ko chalte nahi plz do something 

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#777]
Plz help me me out internet connection is good but still stop at 7 
I am doing sehaj padth plz dosomething ruk gaye beech mei plzzzzdo something 

Please select which platform you are using:-
Web Version

Feedback Type
Plz solve my problem my neetwork is wotking welll but i am doing sehaj path aur karte vella ruk gaya beech mei roj shaamm ko chalte nahi plz do something 

What went wrong?
Plz solve ji i am doing sehaj padth Waheguru Ji ke kripa se karte time ruk gaye plzzz do something sham ke time ruk jata hai plz do something 7 tu bukul bhi nhi chalte Plz help 
 
What should have happened instead?

    
How can the issue be recreated by our team?
Plz helpOnly internet low and clear cache i hab done it 

Which web browser are using?
Chrome 

Operating System
Other

Name
Yukta Pasticha

**Comment by Gauravjeetsingh** [comment]
I think this was because of the API issue, which is solved now. So closing it.
