### ISSUE TITLE
Add ability for banners

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#793]
**Describe the solution you'd like**
Add ability for a notice and an attention banner.

Notice banner should have yellow heading and attention one should have red.

Both should be able to be minimized, yellow close should be remembered. STTM api should be used. 

**Describe alternatives you've considered**
PM needs to decide how this UI works with notifications UI, ie they should work together. Perhaps notifications are the notice/yellow one.

**Comment by gurpreet-hanjra** [comment]
Hello, I would like to work on this. Do we have more information about this feature, maybe designs?

**Comment by saintsoldierx** [comment]
<img width="1679" alt="STTM-alert1" src="https://user-images.githubusercontent.com/27791330/67120065-5fbea580-f19d-11e9-9592-e5eb47d9ed35.png">
<img width="1679" alt="STTM-alert2" src="https://user-images.githubusercontent.com/27791330/67120067-5fbea580-f19d-11e9-88c4-351f61d719d3.png">
<img width="1679" alt="STTM-alert3" src="https://user-images.githubusercontent.com/27791330/67120069-60573c00-f19d-11e9-8b41-3aa57a20e660.png">
 @gurpreet-hanjra

**Comment by saintsoldierx** [comment]
@gurpreet-hanjra would you be able to complete this by the November milestone?

**Comment by gurpreet-hanjra** [comment]
@saintsoldierx Sure, I will look into it. Thank you.

**Comment by saintsoldierx** [comment]
http://api.sikhitothemax.org/messages/web/ or http://api.sikhitothemax.org/messages/web/2018-05-29 to get messages since date

Heres the format: http://api.sikhitothemax.org/messages/desktop/2017-05-29 of whats returned

**Comment by saintsoldierx** [comment]
Friendly bump @gurpreet-hanjra - would love to get this feature implemented soon.

**Comment by gurpreet-hanjra** [comment]
Sorry for the delay. On it!

**Comment by AkalUstat** [comment]
@saintsoldierx do you want all three?

**Comment by saintsoldierx** [comment]
Yes please @AkalUstat but first one is most important - if it's tough to do the other two, then at least get the first one working.

**Comment by AkalUstat** [comment]
K for now ill do the first one. Looks like @gurpreet-hanjra got the looks and basics in so pretty sure i just have to store if user has seen/closed the banner

**Comment by AkalUstat** [comment]
Nvm just saw ur comment on the pr

**Comment by AkalUstat** [comment]
Nvm just saw ur comment on the pr

**Comment by AkalUstat** [comment]
3 Major Problems from #938 
 - Date is wrong (for future) -> the month
- styling -> height = auto, colors
- checking if seen (use expire date as well
@saintsoldierx

**Comment by saintsoldierx** [comment]
@AkalUstat are the issues in your last update still valid or can i close this and mark as done?

**Comment by AkalUstat** [comment]
This one is done

**Comment by Gauravjeetsingh** [comment]
@saintsoldierx This issue slipped my mind, did we decide to do something more in this issue. :thinking: The basic support for showing messages has been working.
