### ISSUE TITLE
Fix and improve Related Shabads

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#810]
<img width="1455" alt="sttm-related" src="https://user-images.githubusercontent.com/27791330/67121623-d5784080-f1a0-11e9-81a6-15dfba3c2662.png">

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/67127735-c1d3d680-f1ae-11e9-85c5-58935bbacaae.png)
Slight update - have the %age match indicated on the bar on left side of the related shabads.

**Comment by tarunsingh5** [comment]
@saintsoldierx do we need to update the milestone here?

**Comment by Gauravjeetsingh** [comment]
New related shabads are now live in prod.
