### ISSUE TITLE
Web User misaligned meanings

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#811]
Line meanings may need to be aligned correctly

Please select which platform you are using:-
Web Version

Feedback Type
misaligned meanings

What went wrong?
https://www.sikhitothemax.org/shabad?id=4064&q=rehs&type=0&source=all&highlight=48377

Punjabi meanings are switched aroundCorrect meaning under the line
 
What should have happened instead?
English meanings are correctly aligned but Punjabi meanings are switched around. 
    
How can the issue be recreated by our team?
Just visit the page I posted in link or search for 'raakhaa ek hamaaraa suaamee'. Only Rahau lines are correct, rest of the meanings in Punjabi are not listed under the correct lines.

Which web browser are using?
Safari 12.1.1

Operating System
Mac OS

Name
Homajeet Singh

**Comment by saintsoldierx** [comment]
Not an issue as such - the explanations in Punjabi were written in context of the shabad, rather than the individual tukks.
