### ISSUE TITLE
Split view mode does not reset

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#814]
**Describe the bug**
On clicking the reset button in display options, it should disable the split view if it's enabled. But it remains unchanged.

**To Reproduce**
1. Go to https://www.sikhitothemax.org/shabad?id=45&q=hrs&type=1&source=G&highlight=485
2. Click on Display options
3. Enable split view
4. Click on reset display button
5. The shabad will still be in split view, it should reset to default view.

**Comment by rajkambo** [comment]
@Gauravjeetsingh its been a while since I've contributed to this repo, do you mind if I take this one on? :D

**Comment by Gauravjeetsingh** [comment]
@rajkambo Sure veerji, go ahead!
