### ISSUE TITLE
Fix a few warnings when deploying

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#815]
Fix a few warnings when deploying (DEV):-

WARNING in ./src/js/components/BaaniLineActions/index.ts 1:0-69
“export ‘IBaaniLineActionsProps’ was not found in ‘./BaaniLineActions’
@ ./src/js/components/Baani.js
@ ./src/js/components/ShabadContent/ShabadContent.js
@ ./src/js/components/ShabadContent/index.ts
@ ./src/js/pages/Shabad/index.js
@ ./src/js/routes.js
@ ./src/js/Root.js
@ ./src/js/index.js
WARNING in ./src/js/components/Fetch/index.ts 1:0-47
“export ‘IFetchProps’ was not found in ‘./Fetch’
@ ./src/js/pages/PageLoader.js
@ ./src/js/pages/Ang/index.js
@ ./src/js/routes.js
@ ./src/js/Root.js
@ ./src/js/index.js
WARNING in ./src/js/components/RelatedShabads/index.ts 3:0-32
“export ‘IRelatedShabadsProps’ was not found in ‘./RelatedShabads’
@ ./src/js/components/ShabadContent/ShabadContent.js
@ ./src/js/components/ShabadContent/index.ts
@ ./src/js/pages/Shabad/index.js
@ ./src/js/routes.js
@ ./src/js/Root.js
@ ./src/js/index.js
WARNING in ./src/js/features/reducers/index.js 94:9-30
“export ‘TOGGLE_UNICODE_OPTION’ was not found in ‘../actions’
@ ./src/js/features/store/index.js
@ ./src/js/index.js
WARNING in ./src/js/features/reducers/index.js 98:18-39
“export ‘TOGGLE_UNICODE_OPTION’ was not found in ‘../actions’
@ ./src/js/features/store/index.js
@ ./src/js/index.js
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
 app (280 KiB)
     chunks/vendor-5f4396f0b453524fbb96.js
     app-5f4396f0b453524fbb96.js

**Comment by rajkambo** [comment]
@saintsoldierx mind if I take this one on?

**Comment by saintsoldierx** [comment]
@rajkambo Please do! :)
