### ISSUE TITLE
Remove Gurmukhi keyboard for English or Ang searching.

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#816]
No need to display Gurmukhi keyboard if English OR Ang is selected for search. For english, you could replace with a QWERTY keyboard but not necessary.

**Comment by gurpreet-hanjra** [comment]
Okay ji. Then can we close this issue? @saintsoldierx @Gauravjeetsingh

**Comment by Gauravjeetsingh** [comment]
It's live now. Closing it out.
