### ISSUE TITLE
Display options hide after scrolling to top on mobile screens.

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#820]
On a smaller screen, all the options (display/font/larivaar) hide on scrolling to top.

![Screenshot from 2019-10-25 21-58-11](https://user-images.githubusercontent.com/1990932/67587974-8e76e600-f772-11e9-9d98-561b86865a22.png)

There's some bug with the auto-hide mechanism. It's supposed to show the controls on scrolling to top. It happens randomly in smaller screens.

**Comment by saintsoldierx** [comment]
Looks good to me now.
