### ISSUE TITLE
If someone searches for a ang value less than 1, change it to 1

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#830]
This doesn't show an error. If we search for an ang -3, it will show the first ang.

But the input and the title bar shows a negative value. 

We can show the validation error, or we can change the value to 1 and then search.
![Screenshot from 2019-11-06 12-59-55](https://user-images.githubusercontent.com/1990932/68278576-9cdcd000-0097-11ea-9eb4-1a04985e80f4.png)

**Comment by amitojsingh** [comment]
Is anyone working on this issue?

**Comment by kee23** [comment]
Haven't started on this yet but am planning to do so. But if someone wants to take over feel free

**Comment by ManjotS** [comment]
API corrects this already

**Comment by Gauravjeetsingh** [comment]
Yeah, we get the first ang from API, for this we need to set input validation from sttm-web, so that we don't get negative numbers in title, and input box,

**Comment by Gauravjeetsingh** [comment]
Ang Validations working in prod.
