### ISSUE TITLE
Web User Translation

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#839]
I am not sure who to contact, but this translation is wrong.  This link translates Mehala Pehla as Third Mehla when it should be first.  

Please select which platform you are using:-
Web Version

Feedback Type
Translation

What went wrong?
Wrong translation

This link translates Mehala Pehla as Third Mehla when it should be first.  Fix translation
 
What should have happened instead?

    
How can the issue be recreated by our team?
https://www.sikhitothemax.org/shabad?id=4657&q=kulha%20dende%20bavaray%20lehnde&type=4&source=all&highlight=55003

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Teginder Dhanoa

**Comment by saintsoldierx** [comment]
change submitted, user has been notified
