### ISSUE TITLE
Add social media links to pages

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#845]
Display latest Instagram posts from STTM IG account, along with links (or widget) for Twitter and FB pages. Design to follow.

**Comment by navdeepsingh** [comment]
@saintsoldierx I want to work on this. Can share the design plz?

**Comment by saintsoldierx** [comment]
Waiting to implement new layout - design will come then so for now this is on hold.

**Comment by saintsoldierx** [comment]
I don't think I want to add IG posts to website anymore. Instead, we should add follow links for IG, Twitter and FB @sikhitothemax

**Comment by gurjit03** [comment]
Closing this for now
