### ISSUE TITLE
all gurmukhi searches in unicode should work just as if they are ascii lipi searches

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#85]
ie searching for ਕ should be same as k

r should be same as ਰ

**Comment by bogas04** [comment]
@navdeepsinghkhalsa Anvaad can help?

**Comment by navdeepsinghkhalsa** [comment]
This should be done at the API level. It won't require any changes on the site, unless we need to update patterns for form validation. @bogas04?

**Comment by ManjotS** [comment]
closing to move to banidb

**Comment by tarunsingh5** [comment]
@ManjotS where are we on this? I'm getting requests for this via whatsapp

**Comment by ManjotS** [comment]
I would like bandidb api v2 to handle this transparently using anvaad
reverse translit.

**Comment by saintsoldierx** [comment]
I just tested and seems this is working. Closing.
