### ISSUE TITLE
Font spacing for gurmukhi is wierd

### ISSUE THREAD

**Issue by AkalUstat** [KhalisFoundation/sttm-web#867]
**Describe the bug**
The font spacing for most of the gurmukhi fonts on dev.sikhitothemax.org (except unicode) is a little too much
![29C71ACE-FD39-448B-BB96-A527AF69082C](https://user-images.githubusercontent.com/43657841/69372595-dc3e1b80-0c56-11ea-92e3-fc7446a4c0f6.png)

**Smartphone (please complete the following information):**
 - Device: iPhone Xr
 - OS: iOS 13.2.3
 - Browser safari
**Additional context**

**Comment by tarunsingh5** [comment]
what's the issue here? space between words?

**Comment by AkalUstat** [comment]
ye it looked wierd. Looks like fixed to me now
