### ISSUE TITLE
Fixes/improvements for new live search

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#873]
Improvements needed for V1 of live search:-

1 - Color theme

Highlighted search results should be  

> color: rgb(1, 102, 155);

Other should be light blue same with opacity 0.3

>  color: rgba(1, 102, 155, 0.3);

2 - Results should be returned after typing in two characters - will be useful in particular for Dasam Granth

3 - Make the scrollbar permanently visible.

4 - Currently, the live search does not take into account first letter selection eg. "first letter" vs "first letter anywhere"

5 - If no results, maybe it can say "no matched results".

6 - If searching in English word, then maybe we can return two rows per result (English on top, Gurbani on bottom)?

**Comment by saintsoldierx** [comment]
For dark mode those colors:

Highlighted:-
> color: #60c8ff
Non highlighted:-
> rgba(96,200,255,0.6)

**Comment by saintsoldierx** [comment]
Any updates on this @Gauravjeetsingh

**Comment by Gauravjeetsingh** [comment]
Working on showing translations. Highlighting translations based on search query is a little tricky. That is taking some time. I have already opened a work in progress PR with these changes, will keep updating that PR as I get something to show.

**Comment by ManjotS** [comment]
Please be sure API call uses livesearch=1
