### ISSUE TITLE
Update NodeJS version 

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-web#879]
Node 8 is moving to End of life [12/31/19](https://nodejs.org/en/about/releases/)

Both travis config and now.json are using node 8. Need to move to at least 10 (preferably 12).

**Comment by saintsoldierx** [comment]
@ManjotS @tsingh777 Please provide a strategy on how we can get this moving along.

**Comment by ManjotS** [comment]
I need tsingh to certify all apps will work with whatever version and we can put that in

**Comment by plug-n-play** [comment]
@ManjotS - can you please specify all apps?

**Comment by ManjotS** [comment]
Sttm-api, banidb-api, telegram bot, sttm web

**Comment by plug-n-play** [comment]
@tsingh777 Assuming all apps are not ready for this switch, using nvm we can still run multiple node versions for each apps on the same machine and this would not be a problem?

**Comment by ManjotS** [comment]
If somebody hands me an implementation plan or instructions, I can deploy.

**Comment by plug-n-play** [comment]
I test environment to play around would help

**Comment by saintsoldierx** [comment]
@ManjotS @tsingh777 who should be leading this effort?

**Comment by gurjit03** [comment]
@saintsoldierx closing this on the sttm-web side as we already have node.js 14
