### ISSUE TITLE
Add rehat maryada section

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#88]
discuss specifics with @navdeepsinghkhalsa who will provide code.

**Comment by ManjotS** [comment]
also add this as an app icon

**Comment by ManjotS** [comment]
no, this ticket is for GUI part, API already provides

**Comment by bogas04** [comment]
Is this a new source? Tankhanama and Rehatnama one? Or it's SGPC Maryada?

**Comment by ManjotS** [comment]
its not in normal path, its /maryada (ie for maryada app)

the main goal is to expose the cordova web app at sttm/maryada which will pull from the maryada api in banidb

This is already working and @navdeepsinghkhalsa said he just needs to release

**Comment by bogas04** [comment]
@manjots okay I'll take it up since I've gained experience with BaniDB api

**Comment by saintsoldierx** [comment]
@ManjotS can you just update on this - is it done, ready to be surfaced?

**Comment by ManjotS** [comment]
It's in v2. Will need to explore if it has everything.

**Comment by saintsoldierx** [comment]
@ManjotS Did you explore and does it have everything we need to get working on this?

**Comment by ManjotS** [comment]
looks like it yes

**Comment by gurjit03** [comment]
@saintsoldierx do we have a UI mockup for this ?

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/115136004-a9c25a80-9fd1-11eb-9124-965480817adf.png)

- Should switch English <> Punjabi when clicked on language.
- Current language should highlight in orange.
- URL should reflect change in language
- Add a copy link / short url like on other STTM shabad pages for people to share.
- Panels should expand collapse (change icon to - if expanded).
- Expand all / collapse all functionality.
- Should be mobile friendly.

**Comment by navdeepsingh** [comment]
@saintsoldierx Is it exposed at BaniDB API?
https://api.khajana.org/v2/maryada - not found

**Comment by tsingh777** [comment]
Apologies, they weren't added to the docs. The paths are 
```
v2/rehats
v2/rehats/:RehatID
v2/rehats/:RehatID/chapters/:ChapterID?
v2/rehats/search/:string
```
I will add them to the docs.
