### ISSUE TITLE
Renable service worker

### ISSUE THREAD

**Issue by bogas04-swiggy** [KhalisFoundation/sttm-web#881]
**Is your feature request related to a problem? Please describe.**
Service worker helps in cases of low network connectivity, say on commute or in a tunnel.

**Describe the solution you'd like**
Enable service worker implementation after proper testing.

**Describe alternatives you've considered**
Caching for longer might be another solution but it isn't ideal.

**Additional context**
https://github.com/KhalisFoundation/sttm-web/blob/93697f2b199b63b7df5c07d17e2e7100475bc629/server/template.js#L139-L148

**Comment by ManjotS** [comment]
I thought we already have service workers?

**Comment by saintsoldierx** [comment]
@ManjotS @tsingh777 could you confirm?

**Comment by ManjotS** [comment]
I see it here: https://github.com/KhalisFoundation/sttm-web/search?q=ServiceWorker&unscoped_q=ServiceWorker

And we removed CDN last year because we wanted to deploy serviceworkers. @turbanpanda can confirm completely.

**Comment by gurjit03** [comment]
@ManjotS @saintsoldierx we do have in the template.js.
