### ISSUE TITLE
Short Ang URL always opens the ang in Guru Granth Sahib ji

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-web#885]
**Describe the bug**
Short URL of Ang 1 of Guru Granth Sahib Ji: http://sttm.co/a/1
Short URL of Ang 1 of Dasam Granth Sahib: http://sttm.co/a/1
Short URL of Ang 1 of Bhai Gurdas Ji Vaaran: http://sttm.co/a/1

All the short URLs of ang view are the same, and thus they always redirect to first ang of Guru Granth Sahib ji.

**To Reproduce**
1. Go to https://www.sikhitothemax.org/ang?ang=1&source=B
2. Click on copy icon next to short URL
3. Open the copied URL in the new tab
4. It will open the first ang of Guru Granth Sahib ji instead of Bhai Gurdas Ji Vaaran

**Expected behavior**
Short url should have a source parameter, to open the Ang in specified source.

**Comment by saintsoldierx** [comment]
Short URL of Ang 1 of Guru Granth Sahib Ji: http://sttm.co/a/1
Short URL of Ang 1 of Dasam Granth Sahib: http://sttm.co/d/1
Short URL of Ang 1 of Bhai Gurdas Ji Vaaran: http://sttm.co/b/1
Short URL of Ang 1 of Bhai Gurdas Singh Ji Vaaran: http://sttm.co/s/1

**Comment by ekas** [comment]
@saintsoldierx Veerji, Just wanted to check with you whether there is a portal to configure the shorten urls against the DNS names. Because, I was trying to locate the shorten urls controller layer which I wasn't able to find.

**Comment by ManjotS** [comment]
https://github.com/KhalisFoundation/sttm-shortener

**Comment by saintsoldierx** [comment]
UPDATED:

Short URL of Ang 1 of Guru Granth Sahib Ji: http://sttm.co/**g**/1
Short URL of Ang 1 of Dasam Granth Sahib: http://sttm.co/**d**/1
Short URL of Ang 1 of Bhai Gurdas Ji Vaaran: http://sttm.co/**v**/1
Short URL of Ang 1 of Bhai Gurdas Singh Ji Vaaran: http://sttm.co/**gs**/1

Short URL of Sunder Gutka is now http://sttm.co/**sg**/

Also, update source value on STTM of Bhai Gurdas Jee Vaaran to 'V' and
Bhai Gurdas Singh Vaaran to 'GS' so 
https://www.sikhitothemax.org/ang?ang=1&**source=V**
https://www.sikhitothemax.org/ang?ang=1&**source=GS**

**Comment by Gauravjeetsingh** [comment]
This is fixed in prod as well. Closing this out.
