### ISSUE TITLE
Ang search causes timeout and not filtering sources

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#889]
1. Display a shabad.
2. Type in characters in search bar at top.
3. Select ang.
4. Spinning mandala times out and causes error.

It should be doing following when user selects ang:-

1. Clear search field to only allow numerics.
2. Filter sources to the same four sources as per index page of STTM.
![image](https://user-images.githubusercontent.com/27791330/70844003-a8868980-1def-11ea-96ad-71b8e53b565d.png)

**Comment by Gauravjeetsingh** [comment]
Filtering sources are now fixed in dev. Timeout is still pending. Will fix that as well.
