### ISSUE TITLE
Live search is auto-selecting the first line.

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#891]
When live search, the first result/line that comes in results should not be auto-selected. When you search a few letters and press enter, the live search is auto-selecting the first line so when you click enter, it goes to the shabad from the live search. When I press enter, it should bring back search results page. Therefore, need to stop the first line from auto-selecting.

**Comment by ManjotS** [comment]
It should only select a live search line on up/down arrow
