### ISSUE TITLE
Failed to parse sourcemap 

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#901]
Seeing error in console:-

DevTools failed to parse SourceMap: http://localhost:8080/headless-content.js.map

![image](https://user-images.githubusercontent.com/27791330/71312914-fe59c380-23e5-11ea-9f06-ab9471c9b7bf.png)

**Comment by saintsoldierx** [comment]
Local issue. Closing

**Comment by startupweb** [comment]
How was this resolved?

**Comment by SandUhrGucker** [comment]
:-( Yes... how was this resolved?

**Comment by saintsoldierx** [comment]
@SandUhrGucker @startupweb , this is not an issue with ur code.

Go to the developer tools (F12 in the browser), then select the three dots in the upper right corner, and go to Settings.

Then, look for Sources, and disable the options: "Enable javascript source maps" "Enable CSS source maps"

If you do that, that would get rid of the warnings. It has nothing to do with your code. Check the developer tools in other pages and you will see the same warning.

**Comment by SandUhrGucker** [comment]
> @SandUhrGucker @startupweb , this is not an issue with ur code.
Thank you very much. I was now able to fix it.
