### ISSUE TITLE
Need help copy and pasting gurmukhi characters

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#907]
Hello, 

I am trying to make slides for my Gurudawara using the Sri Dasam Granth Sahib. Every time I try to copy and paste from PDF's the Gurmukhi is lost and random characters appear. I tried to copy and paste from your site as well and it still won't paste over properly. Do you have a copy that I could use that's in HTML or any other format that will work when copy and pasted? I would greatly appreciate the help.   

Please select which platform you are using:-
Web Version

Feedback Type
Questions

What went wrong?

 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
Jasdeep Brar

**Comment by tarunsingh5** [comment]
assigned to aman singh for prioritization/follow up

**Comment by saintsoldierx** [comment]
Been a while, closing this one.
