### ISSUE TITLE
change default punjabi source

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#914]
Default punjabi should now come from translations.pu.bdb instead of from pu.ss. (or puu.bdb)

going forward, pu.ss will be sahib singh and pu.ft is faridkot tika - both should be available

**Comment by Gauravjeetsingh** [comment]
We don't have any `translations.pu.bdb` in the API response yet. Should I be looking for it somewhere else?

![Screenshot from 2020-01-21 19-33-01](https://user-images.githubusercontent.com/1990932/72811047-dbd8f580-3c84-11ea-8550-278cc357a074.png)

**Comment by ManjotS** [comment]
should be there on dev.

**Comment by tarunsingh5** [comment]
@ManjotS can this be combined w/ your latest issue #1123

**Comment by ManjotS** [comment]
Yes
