### ISSUE TITLE
Sukhmani Sahib crashes with larivaar

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-web#918]
**Describe the bug**
Doesn't load Sukhmani sahib.

**To Reproduce**
Go to https://www.sikhitothemax.org/sundar-gutka/31 and have larivaar enabled. 

**Expected behavior**
Bani should load.
**Screenshots**
![image](https://user-images.githubusercontent.com/2982784/72393931-3d2f2080-36e9-11ea-9d4c-e85f1c61cb69.png)

**Additional context**
```error: ReferenceError: color is not defined at https://www.sikhitothemax.org/assets/js/app-069f9ba031da2f48a3f0.js:1:16900 at Array.map (<anonymous>) at https://www.sikhitothemax.org/assets/js/app-069f9ba031da2f48a3f0.js:1:16614 at li (https://www.sikhitothemax.org/assets/js/chunks/vendor-069f9ba031da2f48a3f0.js:22:56671) at ii (https://www.sikhitothemax.org/assets/js/chunks/vendor-069f9ba031da2f48a3f0.js:22:56492) at oi (https://www.sikhitothemax.org/assets/js/chunks/vendor-069f9ba031da2f48a3f0.js:22:56219) at di (https://www.sikhitothemax.org/assets/js/chunks/vendor-069f9ba031da2f48a3f0.js:22:65482) at Yi (https://www.sikhitothemax.org/assets/js/chunks/vendor-069f9ba031da2f48a3f0.js:22:78334) at Ki (https://www.sikhitothemax.org/assets/js/chunks/vendor-069f9ba031da2f48a3f0.js:22:78711) at ja (https://www.sikhitothemax.org/assets/js/chunks/vendor-069f9ba031da2f48a3f0.js:22:85134)```

**Comment by saintsoldierx** [comment]
Thanks @ekas
