### ISSUE TITLE
Settings for display need to be re-designed

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-web#963]
As we add more and more new features, display is becoming very cluttered - particularly on mobile browsers. Need to redesign the settings panel.

![image](https://user-images.githubusercontent.com/27791330/73789970-96242e80-4754-11ea-8bd7-c52b5c9ba5cb.png)

**Comment by AkalUstat** [comment]
Maybe you could have a separate page for settings ? 
or like have a full-screen overlay for smaller screens?
or maybe an overlay for all screens
