### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#969]
Dear Sir, you have done and are doing an amaaaaazing service (seva.) I find SikhiToTheMax very helpful in my search and understanding of Gurbani.
Here is some feedback on the default view in the web version;
- I'm not sure if English Transliteration is needed to be enabled by default. Whoever wants to read Gurbani that way can enable it themselves. That is just my opinion because I'm a Punjabi Sikh, other groups may have requested it and that's fine.
- I'm using a large desktop screen and I find default fonts to be too large. I end up adjusting font to about 20% of your scale so I can read it properly on my screen.
- Lastly a request for a feature. It would be great to have Shabadarth enabled. I use an Android App called iGranth. On this app when I search Gurbani using the first letters, the app displays shabad-arth along with the search results. So the default view is Gurbani in Gurmukhi at the top, English translation below it, shabad-arath below that, and lastly translation in Punjabi (Gurmukhi.)

This just some feedback, SikhiToTheMax is great 'just as it is.'

Please select which platform you are using:-
Web Version

Feedback Type
Comments

What went wrong?

 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
Harjit Gill

**Comment by saintsoldierx** [comment]
1. At present, I would rather leave translit enabled. Only a couple of clicks to turn off and settings are saved for next time.
2. Font sizing is being addressed in other tickets.
3. If you search in english, results are shown in english. Not sure if it's needed that anyone searching in Gurmukhi would necessarily need translations if they are not searching via translations.
