### ISSUE TITLE
Web User Can’t open random shabdha 

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#972]
Does work 

Please select which platform you are using:-
Mobile App

Feedback Type
Can’t open random shabdha 

What went wrong?
It is not working since 3weeksComes up as something is wrong 
 
What should have happened instead?

    
How can the issue be recreated by our team?
Please fix it

Which web browser are using?
Safari 

Operating System
Other

Name
Sukh  Pandher

**Comment by saintsoldierx** [comment]
Should be working.
