### ISSUE TITLE
Hindi Translations

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#976]
Please select which platform you are using:-
Desktop Version

Feedback Type
Enhancements

What went wrong?
Hi,
Please add Hindi translation for SGGS to your website STTM. 

You can use Hindi translation by Prof Sahib Singh / Bhupinder Singh from this website -
http://www.gurugranthdarpan.net/hindi/index.html

I am trying to add Hindi translation to my website www.dekho-ji.com but it will take time. It will be better if Hindi translation can be added directly to Banidb / api.banidb.com database so that everyone can refer it from there.

Thanks & Regards,
Navneet
Founder-Owner
www.dekho-ji.com
helpdesk@dekho-ji.com

 
What should have happened instead?

    
How can the issue be recreated by our team?
Refer above

Which web browser are using?
 

Operating System

Name
Navneet Singh

**Comment by saintsoldierx** [comment]
As per Manjot, this is currently in progress by Gurjaspal Singh

**Comment by tarunsingh5** [comment]
@tsingh777 - did we get around to uploading all of this into the db?
