### ISSUE TITLE
Ang Search Bug

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-web#980]
Please select which platform you are using:-
Web Version

Feedback Type
Bug Reports

What went wrong?
Sharing ang link from Bhai Gurdas Ji Vaaran results in link for SGGS ji
 
What should have happened instead?
It should have opened Bhai Sahibs Vaaran
    
How can the issue be recreated by our team?
Open web app
Search Bhai Sahibs Vaaran by ang
Copy link url
Open anywhere else
Unexpected page opens

Which web browser are using?
Chrome 

Operating System
Other

Name
Jasdeep Singj

**Comment by saintsoldierx** [comment]
Fixed.
